"use client";
import {useEffect,useRef,useState} from "react";
import {analyzeBill,type BillAnalysisResult} from "@/lib/bill-analysis-v3";
import {repairBillPrices} from "@/lib/bill-price-repair";
import {getBillSession,saveBillSession} from "@/lib/bill-session";
function fmt(k:keyof BillAnalysisResult,v:string|number|null){if(v===null)return "Nicht erkannt";if(k==="annualConsumptionKwh")return `${Number(v).toLocaleString("de-DE")} kWh`;if(k==="workPriceCtPerKwh")return `${Number(v).toFixed(2).replace(".",",")} ct/kWh`;if(k==="basePriceEurPerYear")return `${Number(v).toFixed(2).replace(".",",")} € / Jahr`;return String(v).replace(/\s-\s/g," – ");}
function timeout<T>(p:Promise<T>,ms:number){return Promise.race([p,new Promise<T>((_,r)=>setTimeout(()=>r(new Error("TIMEOUT")),ms))]);}
function accepted(f:File){return ["application/pdf","image/jpeg","image/png","image/webp"].includes(f.type)||/\.(pdf|jpe?g|png|webp)$/i.test(f.name);}
function setInput(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));}
function applyData(r:BillAnalysisResult){const v=r.annualConsumptionKwh.value;if(typeof v!=="number")return;const inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input[type="number"]'));const target=inputs.find(i=>/verbrauch|strom|gas/i.test(`${i.placeholder} ${i.name} ${i.getAttribute("aria-label")||""}`));if(target)setInput(target,String(v));}
function merge(rs:BillAnalysisResult[]){const out={...rs[0]};for(const r of rs.slice(1))for(const k of Object.keys(out) as Array<keyof BillAnalysisResult>)if(out[k].value===null&&r[k].value!==null)out[k]=r[k];return out;}
export default function BillUploadReference({onContinue}:{onContinue?:()=>void}){
 const inputRef=useRef<HTMLInputElement>(null);const[files,setFiles]=useState<File[]>([]);const[analysis,setAnalysis]=useState<BillAnalysisResult|null>(null);const[status,setStatus]=useState<"idle"|"ready"|"analyzing"|"done">("idle");const[error,setError]=useState("");
 useEffect(()=>{getBillSession().then(s=>{if(s.files.length){setFiles(s.files);if(s.meta?.analysis){setAnalysis(s.meta.analysis);setStatus("done");}}}).catch(()=>undefined)},[]);
 const add=(incoming:File[])=>{const valid=incoming.filter(accepted).filter(f=>f.size<=10*1024*1024);const next=[...files,...valid].filter((f,i,a)=>i===a.findIndex(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)).slice(0,12);setFiles(next);setAnalysis(null);setStatus(next.length?"ready":"idle");void saveBillSession(next,null);};
 const analyze=async()=>{if(!files.length||status==="analyzing")return;setStatus("analyzing");setError("");try{const rs:BillAnalysisResult[]=[];for(const f of files){try{rs.push(await timeout(analyzeBill(f),150000))}catch{}}if(!rs.length)throw new Error("NO_DATA");const m=merge(rs);const repairs=await Promise.all(files.map(repairBillPrices));const wp=repairs.map(x=>x.workPriceCtPerKwh).filter((x):x is number=>typeof x==="number"&&x>=5&&x<=100);const bp=repairs.map(x=>x.basePriceEurPerYear).filter((x):x is number=>typeof x==="number"&&x>=10&&x<=10000);if(wp.length)m.workPriceCtPerKwh={value:Math.max(...wp),confidence:"high",source:"document"};if(bp.length)m.basePriceEurPerYear={value:Math.max(...bp),confidence:"high",source:"document"};setAnalysis(m);setStatus("done");applyData(m);await saveBillSession(files,m);}catch{setStatus("ready");setError("Die Rechnung konnte nicht ausgelesen werden. Bitte eine PDF oder ein scharfes Foto hochladen.")}};
 const consumption=analysis?fmt("annualConsumptionKwh",analysis.annualConsumptionKwh.value):"Nicht erkannt";const work=analysis?fmt("workPriceCtPerKwh",analysis.workPriceCtPerKwh.value):"Nicht erkannt";const base=analysis?fmt("basePriceEurPerYear",analysis.basePriceEurPerYear.value):"Nicht erkannt";const provider=analysis?.provider.value?String(analysis.provider.value):"Energierechnung";const annual=typeof analysis?.annualConsumptionKwh.value==="number"&&typeof analysis?.workPriceCtPerKwh.value==="number"&&typeof analysis?.basePriceEurPerYear.value==="number"?`${Math.round((analysis.annualConsumptionKwh.value*analysis.workPriceCtPerKwh.value/100+analysis.basePriceEurPerYear.value)).toLocaleString("de-DE")} €`:"Nicht erkannt";
 return <div className="mt-4 text-left">
  {!analysis&&<div className="rounded-[24px] border border-white/10 bg-white/[.035] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold text-white">Rechnung hochladen</p><p className="mt-1 text-xs text-slate-400">PDF, JPG, PNG oder WEBP · bis zu 12 Dateien</p></div><div className="flex gap-2"><button type="button" onClick={()=>inputRef.current?.click()} className="rounded-xl border border-[#19b7ff]/35 bg-[#19b7ff]/10 px-4 py-2.5 text-sm font-bold text-[#8ce4ff]">Rechnung auswählen</button>{files.length>0&&<button type="button" onClick={analyze} disabled={status==="analyzing"} className="rounded-xl bg-[#19b7ff] px-4 py-2.5 text-sm font-bold text-[#03101c]">{status==="analyzing"?"Wird geprüft …":"Rechnung prüfen"}</button>}</div></div><input ref={inputRef} type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,.pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{add(Array.from(e.target.files||[]));e.currentTarget.value=""}}/>{error&&<p className="mt-2 text-xs text-red-300">{error}</p>}</div>}
  {analysis&&<section className="overflow-hidden rounded-[1.8rem] border border-[#1b3b58] bg-[#061a2d] p-7 shadow-2xl shadow-black/25 sm:p-9">
   <div className="flex items-start justify-between gap-5"><div><p className="text-[14px] uppercase tracking-[.28em] text-[#91a4c0]">Rechnungsanalyse</p><h2 className="mt-4 text-[30px] font-extrabold leading-none tracking-[-.035em] text-white sm:text-[34px]">{provider}</h2></div><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-[20px] bg-[#0b3150] text-[34px] leading-none text-[#67d7ff]">✦</div></div>
   <div className="mt-10 border-t border-[#20384e] pt-8"><div className="space-y-4">
    {[['Jahresverbrauch',consumption],['Arbeitspreis',work],['Grundpreis',base],['Jahreskosten',annual]].map(([label,value])=><div key={label} className="flex min-h-[82px] items-center justify-between gap-6 rounded-[28px] border border-[#213d56] bg-[#102238] px-6 py-5 sm:px-8"><span className="text-[20px] font-medium text-[#9aabc3] sm:text-[23px]">{label}</span><span className="text-right text-[22px] font-extrabold tracking-[-.025em] text-white sm:text-[25px]">{value}</span></div>)}
   </div><p className="mt-6 text-[17px] text-[#758ba8] sm:text-[19px]">Darstellung dient als Beispiel.</p></div>
   {onContinue&&<button type="button" onClick={onContinue} className="mt-7 w-full rounded-full bg-[#19b7ff] px-6 py-3.5 font-bold text-[#03101c]">Mit diesen Daten weiter</button>}
  </section>}
 </div>;
}
