"use client";
import {useEffect,useRef,useState} from "react";
import {analyzeBill,type BillAnalysisResult} from "@/lib/bill-analysis-v3";
import {repairBillPricesV2} from "@/lib/bill-price-repair-v2";
import {repairBillConsumption} from "@/lib/bill-consumption-repair";
import {BILL_ANALYSIS_VERSION,getBillSession,saveBillSession} from "@/lib/bill-session";
import {BillAnalysisResult as BillAnalysisView} from "@/components/BillAnalysisResult";

const timeout=<T,>(p:Promise<T>,ms:number)=>Promise.race([p,new Promise<T>((_,r)=>setTimeout(()=>r(Error("TIMEOUT")),ms))]);
const accepted=(f:File)=>["application/pdf","image/jpeg","image/png","image/webp"].includes(f.type)||/\.(pdf|jpe?g|png|webp)$/i.test(f.name);
const merge=(rs:BillAnalysisResult[])=>{const o={...rs[0]};for(const r of rs.slice(1))for(const k of Object.keys(o) as Array<keyof BillAnalysisResult>)if(o[k].value==null&&r[k].value!=null)o[k]=r[k];return o};
const setInput=(i:HTMLInputElement,v:string)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(i,v);i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))};
const apply=(r:BillAnalysisResult)=>{const v=r.annualConsumptionKwh.value;if(typeof v!=="number")return;const inputs=Array.from(document.querySelectorAll<HTMLInputElement>('input[type="number"]'));const target=inputs.find(i=>/verbrauch|strom|gas/i.test(`${i.placeholder} ${i.name} ${i.getAttribute("aria-label")||""}`));if(target)setInput(target,String(v))};

export default function BillUploadFinal(){
 const ref=useRef<HTMLInputElement>(null);const[files,setFiles]=useState<File[]>([]);const[a,setA]=useState<BillAnalysisResult|null>(null);const[status,setStatus]=useState<"idle"|"uploading"|"analyzing"|"success"|"error">("idle");const[error,setError]=useState("");
 useEffect(()=>{getBillSession().then(s=>{if(s.files.length)setFiles(s.files);if(s.meta?.analysisVersion===BILL_ANALYSIS_VERSION&&s.meta.analysis){setA(s.meta.analysis);setStatus("success")}else if(s.files.length)void saveBillSession(s.files,null)}).catch(()=>{})},[]);
 const add=(xs:File[])=>{const file=xs[0];if(!file)return;if(!accepted(file)){setError("Datei konnte nicht gelesen werden. Bitte lade eine PDF oder ein klares Foto hoch.");setStatus("error");return}if(file.size>10*1024*1024){setError("Die Datei ist zu groß. Bitte lade eine Datei bis 10 MB hoch.");setStatus("error");return}setStatus("uploading");setError("");setFiles([file]);setA(null);void saveBillSession([file],null);setTimeout(()=>setStatus("idle"),0)};
 const remove=()=>{setFiles([]);setA(null);setError("");setStatus("idle");if(ref.current)ref.current.value="";void saveBillSession([],null)};
 const run=async()=>{if(!files.length||status==="analyzing")return;setStatus("analyzing");setError("");try{const rs:BillAnalysisResult[]=[];for(const f of files){try{rs.push(await timeout(analyzeBill(f),150000))}catch{}}if(!rs.length)throw Error();const m=merge(rs);const[prices,consumptions]=await Promise.all([Promise.all(files.map(repairBillPricesV2)),Promise.all(files.map(repairBillConsumption))]);const wp=prices.map(x=>x.workPriceCtPerKwh).filter((x):x is number=>typeof x==="number"&&x>=5&&x<=100);const bp=prices.map(x=>x.basePriceEurPerYear).filter((x):x is number=>typeof x==="number"&&x>=10&&x<=10000);const ck=consumptions.filter((x):x is number=>typeof x==="number"&&x>=100&&x<=100000);if(wp.length)m.workPriceCtPerKwh={value:Math.max(...wp),confidence:"high",source:"document"};if(bp.length)m.basePriceEurPerYear={value:Math.max(...bp),confidence:"high",source:"document"};if(ck.length)m.annualConsumptionKwh={value:Math.max(...ck),confidence:"high",source:"document"};setA(m);setStatus("success");apply(m);await saveBillSession(files,m)}catch{setStatus("error");setError("Datei konnte nicht gelesen werden. Bitte lade ein klares Foto oder PDF hoch.")}};
 return <div className="mt-4 text-left">
 {!a&&<div className="min-h-[300px] rounded-[24px] border border-white/10 bg-white/[.035] p-5"><div className="flex min-h-[260px] flex-col items-center justify-center text-center"><p className="font-bold text-white">Rechnung hochladen</p><p className="mt-2 text-xs text-slate-400">PDF, JPG, PNG oder WEBP · bis 10 MB</p><button type="button" onClick={()=>ref.current?.click()} disabled={status==="analyzing"} className="mt-5 rounded-xl bg-[#19b7ff] px-5 py-3 text-sm font-bold text-[#03101c]">{files.length?"Andere Datei auswählen":"Datei auswählen"}</button><input ref={ref} type="file" multiple={false} accept=".pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{add(Array.from(e.target.files||[]));e.currentTarget.value=""}}/>{files.length>0&&<div className="mt-4 w-full max-w-md rounded-xl border border-white/10 bg-white/[.035] p-3"><div className="flex items-center justify-between gap-3"><span className="min-w-0 truncate text-xs text-slate-300">{files[0].name}</span><button type="button" onClick={remove} disabled={status==="analyzing"} aria-label="Datei löschen" className="shrink-0 rounded-lg px-2 py-1 text-xs font-bold text-slate-500 hover:bg-red-500/10 hover:text-red-300">Löschen</button></div><button type="button" onClick={run} disabled={status==="analyzing"} className="mt-3 w-full rounded-xl border border-[#19b7ff]/40 px-4 py-2.5 text-xs font-bold text-[#8ce4ff]">{status==="analyzing"?"Wird geprüft …":"Rechnung prüfen"}</button></div>}{error&&<div className="mt-4 flex items-center gap-3 rounded-xl bg-red-500/10 p-3 text-xs text-red-300"><span>{error}</span><button type="button" onClick={()=>ref.current?.click()} className="shrink-0 font-bold text-white underline">Erneut versuchen</button></div>}</div></div>}
 {a&&<BillAnalysisView analysis={a} onSubmitted={()=>{}}/>}
 {a&&status==="success"&&<button type="button" onClick={()=>{setStatus("analyzing");void run()}} className="mt-3 w-full rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-xs font-bold text-slate-300">Analyse erneut durchführen</button>}
 {a&&files.length>0&&<div className="mt-3 flex gap-2"><button type="button" onClick={()=>ref.current?.click()} className="flex-1 rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-xs font-bold text-slate-300">Andere Datei auswählen</button><button type="button" onClick={remove} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-slate-500 hover:border-red-400/30 hover:text-red-300">Löschen</button><input ref={ref} type="file" multiple={false} accept=".pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{add(Array.from(e.target.files||[]));e.currentTarget.value=""}}/></div>}
 </div>;
}
