"use client";
import {useEffect,useRef,useState} from "react";
import {analyzeBill,type BillAnalysisResult} from "@/lib/bill-analysis-v3";
import {repairBillPrices} from "@/lib/bill-price-repair";
import {getBillSession,saveBillSession} from "@/lib/bill-session";

const fmt=(k:keyof BillAnalysisResult,v:string|number|null)=>{if(v==null)return "Nicht erkannt";if(k==="annualConsumptionKwh")return `${Number(v).toLocaleString("de-DE")} kWh`;if(k==="workPriceCtPerKwh")return `${Number(v).toFixed(2).replace(".",",")} ct/kWh`;if(k==="basePriceEurPerYear")return `${Number(v).toFixed(2).replace(".",",")} € / Jahr`;return String(v).replace(/\s-\s/g," – ")};
const timeout=<T,>(p:Promise<T>,ms:number)=>Promise.race([p,new Promise<T>((_,r)=>setTimeout(()=>r(new Error("TIMEOUT")),ms))]);
const accepted=(f:File)=>["application/pdf","image/jpeg","image/png","image/webp"].includes(f.type)||/\.(pdf|jpe?g|png|webp)$/i.test(f.name);
const merge=(rs:BillAnalysisResult[])=>{const o={...rs[0]};for(const r of rs.slice(1))for(const k of Object.keys(o) as Array<keyof BillAnalysisResult>)if(o[k].value==null&&r[k].value!=null)o[k]=r[k];return o};
const setInput=(i:HTMLInputElement,v:string)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(i,v);i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))};
const apply=(r:BillAnalysisResult)=>{const v=r.annualConsumptionKwh.value;if(typeof v!=="number")return;const i=Array.from(document.querySelectorAll<HTMLInputElement>('input[type="number"]')).find(x=>/verbrauch|strom|gas/i.test(`${x.placeholder} ${x.name} ${x.getAttribute("aria-label")||""}`));if(i)setInput(i,String(v))};
function Spark(){return <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-[20px] bg-[#0b3150] text-[35px] leading-none text-[#67d7ff]">✦</div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex min-h-[82px] items-center justify-between gap-6 rounded-[28px] border border-[#213d56] bg-[#102238] px-6 py-5 sm:min-h-[92px] sm:px-8"><span className="text-[20px] font-medium leading-tight text-[#9aabc3] sm:text-[23px]">{label}</span><span className="max-w-[55%] text-right text-[22px] font-extrabold leading-tight tracking-[-.025em] text-white sm:text-[25px]">{value}</span></div>}
function Trash(){return <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5"><path d="M4 7h16M9 7V4h6v3m-9 0 1 14h10l1-14M10 11v6M14 11v6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export default function BillUploadExact({onContinue}:{onContinue?:()=>void}){
 const ref=useRef<HTMLInputElement>(null);const[files,setFiles]=useState<File[]>([]);const[a,setA]=useState<BillAnalysisResult|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{getBillSession().then(s=>{if(s.files.length){setFiles(s.files);if(s.meta?.analysis)setA(s.meta.analysis)}}).catch(()=>{})},[]);
 const add=(xs:File[])=>{const v=xs.filter(accepted).filter(x=>x.size<=10*1024*1024);const n=[...files,...v].filter((f,i,z)=>i===z.findIndex(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)).slice(0,12);setFiles(n);setA(null);setError("");void saveBillSession(n,null)};
 const remove=(index:number)=>{const n=files.filter((_,i)=>i!==index);setFiles(n);setA(null);setError("");void saveBillSession(n,null)};
 const run=async()=>{if(!files.length||busy)return;setBusy(true);setError("");try{const rs:BillAnalysisResult[]=[];for(const f of files){try{rs.push(await timeout(analyzeBill(f),150000))}catch{}}if(!rs.length)throw Error();const m=merge(rs);const p=await Promise.all(files.map(repairBillPrices));const wp=p.map(x=>x.workPriceCtPerKwh).filter((x):x is number=>typeof x==="number"&&x>=5&&x<=100);const bp=p.map(x=>x.basePriceEurPerYear).filter((x):x is number=>typeof x==="number"&&x>=10&&x<=10000);if(wp.length)m.workPriceCtPerKwh={value:Math.max(...wp),confidence:"high",source:"document"};if(bp.length)m.basePriceEurPerYear={value:Math.max(...bp),confidence:"high",source:"document"};setA(m);apply(m);await saveBillSession(files,m)}catch{setError("Die Rechnung konnte nicht ausgelesen werden. Bitte eine PDF oder ein scharfes Foto hochladen.")}finally{setBusy(false)}};
 const provider=a?.provider.value?String(a.provider.value):"Energierechnung";const consumption=fmt("annualConsumptionKwh",a?.annualConsumptionKwh.value??null);const work=fmt("workPriceCtPerKwh",a?.workPriceCtPerKwh.value??null);const base=fmt("basePriceEurPerYear",a?.basePriceEurPerYear.value??null);const annual=typeof a?.annualConsumptionKwh.value==="number"&&typeof a?.workPriceCtPerKwh.value==="number"&&typeof a?.basePriceEurPerYear.value==="number"?`${Math.round(a.annualConsumptionKwh.value*a.workPriceCtPerKwh.value/100+a.basePriceEurPerYear.value).toLocaleString("de-DE")} €`:"Nicht erkannt";
 return <div className="mt-4 text-left">
 {!a&&<div className="rounded-[24px] border border-white/10 bg-white/[.035] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold text-white">Rechnung hochladen</p><p className="mt-1 text-xs text-slate-400">PDF, JPG, PNG oder WEBP · bis zu 12 Dateien</p></div><div className="flex gap-2"><button type="button" onClick={()=>ref.current?.click()} className="rounded-xl border border-[#19b7ff]/35 bg-[#19b7ff]/10 px-4 py-2.5 text-sm font-bold text-[#8ce4ff]">{files.length?"Weitere Datei":"Rechnung auswählen"}</button>{files.length>0&&<button type="button" onClick={run} disabled={busy} className="rounded-xl bg-[#19b7ff] px-4 py-2.5 text-sm font-bold text-[#03101c]">{busy?"Wird geprüft …":"Rechnung prüfen"}</button>}</div></div><input ref={ref} type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp,.pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{add(Array.from(e.target.files||[]));e.currentTarget.value=""}}/>{error&&<p className="mt-2 text-xs text-red-300">{error}</p>}</div>}
 {files.length>0&&<section className="mt-3 rounded-[18px] border border-white/10 bg-[#061426]/90 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#91a4c0]">Dateien ({files.length})</p><button type="button" onClick={()=>ref.current?.click()} className="text-xs font-bold text-[#67d7ff]">+ Datei hinzufügen</button></div><div className="space-y-1.5">{files.map((f,i)=><div key={`${f.name}-${f.lastModified}-${i}`} className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.025] px-3 py-2"><span className="min-w-0 flex-1 truncate text-xs font-medium text-slate-200">{f.name}</span><span className="shrink-0 text-[11px] text-slate-500">{Math.max(1,Math.round(f.size/1024))} KB</span><button type="button" onClick={()=>remove(i)} aria-label={`${f.name} löschen`} title="Datei löschen" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-slate-400 transition hover:bg-red-500/10 hover:text-red-300"><Trash/></button></div>)}</div></section>}
 {a&&<section className="mt-4 overflow-hidden rounded-[2rem] border border-[#1b3b58] bg-[#061a2d] p-7 shadow-2xl shadow-black/25 sm:p-9">
   <div className="flex items-start justify-between gap-5"><div><p className="text-[14px] uppercase tracking-[.28em] text-[#91a4c0]">Rechnungsanalyse</p><h3 className="mt-4 text-[30px] font-extrabold leading-none tracking-[-.035em] text-white sm:text-[34px]">{provider}</h3></div><Spark/></div>
   <div className="mt-10 border-t border-[#20384e] pt-8"><div className="space-y-4"><Row label="Jahresverbrauch" value={consumption}/><Row label="Arbeitspreis" value={work}/><Row label="Grundpreis" value={base}/><Row label="Jahreskosten" value={annual}/></div><p className="mt-6 text-[17px] text-[#758ba8] sm:text-[19px]">Darstellung dient als Beispiel.</p></div>
 </section>}
 {a&&onContinue&&<button type="button" onClick={onContinue} className="mt-4 w-full rounded-xl bg-[#19b7ff] px-4 py-3.5 text-sm font-bold text-[#03101c]">Mit diesen Daten weiter</button>}
 </div>
}