export type BillAnalysisField={value:string|number|null;confidence:"high"|"medium"|"low"|"unknown";source:"document"|"not_detected"};
export type BillAnalysisResult={energyType:BillAnalysisField;provider:BillAnalysisField;tariffName:BillAnalysisField;annualConsumptionKwh:BillAnalysisField;workPriceCtPerKwh:BillAnalysisField;basePriceEurPerYear:BillAnalysisField;monthlyPaymentEur:BillAnalysisField;billingPeriod:BillAnalysisField;contractEnd:BillAnalysisField;cancellationPeriod:BillAnalysisField;address:BillAnalysisField};
export const BILL_ANALYSIS_FIELDS:Array<keyof BillAnalysisResult>=["energyType","provider","tariffName","annualConsumptionKwh","workPriceCtPerKwh","basePriceEurPerYear","monthlyPaymentEur","billingPeriod","contractEnd","cancellationPeriod","address"];
type Confidence=BillAnalysisField["confidence"];
type Hit={value:number;score:number;index:number};
const OCR_CDN="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";
const PDF_CDN="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.54/build/pdf.mjs";
let ocrLoadPromise:Promise<void>|null=null;let pdfLoadPromise:Promise<any>|null=null;
declare global{interface Window{Tesseract?:any}}
const emptyField=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"});
const field=(v:string|number|null,c:Confidence="medium"):BillAnalysisField=>v===null||v===""?emptyField():{value:v,confidence:c,source:"document"};
export function emptyBillAnalysis():BillAnalysisResult{return{energyType:emptyField(),provider:emptyField(),tariffName:emptyField(),annualConsumptionKwh:emptyField(),workPriceCtPerKwh:emptyField(),basePriceEurPerYear:emptyField(),monthlyPaymentEur:emptyField(),billingPeriod:emptyField(),contractEnd:emptyField(),cancellationPeriod:emptyField(),address:emptyField()};}
function loadScript(src:string):Promise<void>{if(typeof document==="undefined")return Promise.reject(new Error("OCR_LIBRARY_LOAD_FAILED"));if(window.Tesseract)return Promise.resolve();if(ocrLoadPromise)return ocrLoadPromise;ocrLoadPromise=new Promise((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>(`script[data-cpm-ocr="${src}"]`);if(existing){existing.addEventListener("load",()=>resolve(),{once:true});existing.addEventListener("error",()=>reject(new Error("OCR_LIBRARY_LOAD_FAILED")),{once:true});return;}const s=document.createElement("script");s.src=src;s.async=true;s.dataset.cpmOcr=src;s.onload=()=>resolve();s.onerror=()=>reject(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(s);});return ocrLoadPromise;}
async function loadPdfJs():Promise<any>{if(pdfLoadPromise)return pdfLoadPromise;const importer=new Function("u","return import(u)") as(u:string)=>Promise<any>;pdfLoadPromise=importer(PDF_CDN);return pdfLoadPromise;}
function canvasCopy(source:unknown):HTMLCanvasElement|null{if(typeof document==="undefined")return null;if(!(source instanceof HTMLCanvasElement)&&!(source instanceof HTMLImageElement))return null;const c=document.createElement("canvas");c.width=source instanceof HTMLCanvasElement?source.width:(source.naturalWidth||source.width);c.height=source instanceof HTMLCanvasElement?source.height:(source.naturalHeight||source.height);const x=c.getContext("2d");if(!x)return null;x.drawImage(source,0,0);return c;}
function enhance(source:unknown,mode:"color"|"gray"|"threshold"):HTMLCanvasElement|unknown{const original=canvasCopy(source);if(!original)return source;const scale=2,c=document.createElement("canvas");c.width=Math.ceil(original.width*scale);c.height=Math.ceil(original.height*scale);const x=c.getContext("2d");if(!x)return original;x.imageSmoothingEnabled=true;x.drawImage(original,0,0,c.width,c.height);if(mode==="color")return c;const image=x.getImageData(0,0,c.width,c.height);for(let i=0;i<image.data.length;i+=4){const l=.299*image.data[i]+.587*image.data[i+1]+.114*image.data[i+2];const v=mode==="threshold"?(l<175?0:255):Math.max(0,Math.min(255,(l-128)*1.45+128));image.data[i]=image.data[i+1]=image.data[i+2]=v;}x.putImageData(image,0,0);return c;}
async function imageCanvas(file:File):Promise<HTMLCanvasElement>{return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{const c=document.createElement("canvas");c.width=i.naturalWidth||i.width;c.height=i.naturalHeight||i.height;const x=c.getContext("2d");URL.revokeObjectURL(u);if(!x)return reject(new Error("IMAGE_DECODE_FAILED"));x.drawImage(i,0,0);resolve(c);};i.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("IMAGE_DECODE_FAILED"));};i.src=u;});}
async function createWorker():Promise<any>{await loadScript(OCR_CDN);if(!window.Tesseract)throw new Error("OCR_LIBRARY_LOAD_FAILED");return window.Tesseract.createWorker("deu");}
async function recognizeWithWorker(worker:any,source:unknown):Promise<string>{const texts:string[]=[];for(const mode of ["color","gray","threshold"] as const){const r=await worker.recognize(enhance(source,mode),{rotateAuto:true},{tessedit_pageseg_mode:"6",preserve_interword_spaces:"1",user_defined_dpi:"300"});const t=String(r?.data?.text||"");if(t.trim())texts.push(t);if(/arbeit\s*spreis|verbrauchs\s*preis|grund\s*preis|jahres\s*verbrauch/i.test(t)&&/(?:ct\s*\/\s*kWh|cent\s*\/\s*kWh|€\s*\/\s*kWh)/i.test(t))break;}return texts.join("\n");}
async function recognizeImage(file:File):Promise<string>{const c=await imageCanvas(file),w=await createWorker();try{return await recognizeWithWorker(w,c);}finally{await w.terminate();}}
async function extractPdfText(file:File):Promise<string>{const pdfjs=await loadPdfJs(),pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages:string[]=[];for(let n=1;n<=Math.min(12,pdf.numPages);n++){const page=await pdf.getPage(n),content=await page.getTextContent(),text=(content.items as any[]).map(item=>typeof item?.str==="string"?item.str:"").join(" ").replace(/\s+/g," ").trim();if(text)pages.push(text);}return pages.join("\n");}
async function renderPdfForOcr(file:File):Promise<string>{const pdfjs=await loadPdfJs(),pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,w=await createWorker(),pages:string[]=[];try{for(let n=1;n<=Math.min(12,pdf.numPages);n++){const page=await pdf.getPage(n),v=page.getViewport({scale:2.4}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const x=c.getContext("2d");if(!x)continue;await page.render({canvasContext:x,viewport:v}).promise;pages.push(await recognizeWithWorker(w,c));}}finally{await w.terminate();}return pages.join("\n");}
function clean(t:string){return t.replace(/\u00a0/g," ").replace(/[|]/g," ").replace(/[‐‑‒–—]/g,"-").replace(/\r/g,"").replace(/k\s*[vw]\s*[whn]/gi,"kWh").replace(/\b(?:kwh|kvvh|kvwh|kwn|kvn)\b/gi,"kWh").replace(/grund[o0]reis|grundpre[i1]s|grundoeis/gi,"Grundpreis").replace(/arbeit\s*(?:s|ss)?\s*pre[i1]s|arbeitspre[il]s|ar[bp]atspre[i1]s/gi,"Arbeitspreis").replace(/verbrauch\s*spre[i1]s|verbrauchspre[i1]s/gi,"Verbrauchspreis").replace(/jahresverh?rauch|jahresverhrauch/gi,"Jahresverbrauch").replace(/str[o0]m/gi,"Strom").replace(/e\s*[.]?\s*o\s*n/gi,"E.ON").replace(/c\s*t\s*\/\s*k\s*[vw]\s*[whn]/gi,"ct/kWh").replace(/cent\s*\/\s*kWh/gi,"ct/kWh").replace(/€\s*\/\s*kWh/gi,"€/kWh").replace(/[ \t]+/g," ");}
function num(raw:string){let s=raw.replace(/\s/g,"").replace(/[^0-9,.-]/g,"");if(!s)return null;const comma=s.lastIndexOf(","),dot=s.lastIndexOf(".");if(comma>=0&&dot>=0)s=comma>dot?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"");else if(comma>=0)s=s.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}\.\d{3}$/.test(s))s=s.replace(".","");const v=Number(s);return Number.isFinite(v)?v:null;}
function dates(t:string){const out:Array<{raw:string;days:number}> = [];for(const m of t.matchAll(/(\d{1,2}[./]\d{1,2}[.]\d{4})\s*(?:-|bis)\s*(\d{1,2}[./]\d{1,2}[.]\d{4})/g)){const p=(s:string)=>{const[d,mo,y]=s.split(/[./]/).map(Number);return new Date(y,mo-1,d).getTime();};const a=p(m[1]),b=p(m[2]);if(a&&b)out.push({raw:`${m[1].replace(/\//g,".")} - ${m[2].replace(/\//g,".")}`,days:Math.abs(b-a)});}return out;}
function annual(t:string):BillAnalysisField{const h:Hit[]=[];const add=(v:number|null,score:number,index:number)=>{if(v!==null&&v>=300&&v<=100000)h.push({value:v,score,index});};for(const m of t.matchAll(/(?:Jahresverbrauch|Verbrauch\/Menge|Verbrauch\s+im\s+Abrechnungsjahr|Ihre\s+Verbrauchsmengen|Summe)[\s\S]{0,500}/gi))for(const n of m[0].matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d{4,6}(?:[.,]\d+)?)\s*kWh/gi))add(num(n[1]),/summe/i.test(m[0])?650:500,(m.index??0)+(n.index??0));for(const n of t.matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d{4,6}(?:[.,]\d+)?)\s*kWh/gi))add(num(n[1]),80,n.index??0);if(!h.length)return emptyField();h.sort((a,b)=>b.score-a.score||b.index-a.index);return field(h[0].value,h[0].score>=500?"high":"medium");}
function work(t:string):BillAnalysisField{const h:Hit[]=[];const add=(v:number|null,score:number,index:number)=>{if(v!==null&&v>=5&&v<=60)h.push({value:v,score,index});};for(const m of t.matchAll(/(?:Arbeitspreis|Verbrauchspreis)[\s\S]{0,500}/gi)){const s=m[0],base=m.index??0;for(const n of s.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi))add(num(n[1]),700,base+(n.index??0));for(const n of s.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:€|EUR)\s*(?:\/\s*)?kWh/gi))add((num(n[1])??0)*100,680,base+(n.index??0));for(const n of s.matchAll(/(\d{1,3}(?:[.,]\d{3})+(?:[.,]\d+)?)\s*kWh\s*(?:x|×|\*)\s*(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*\/\s*kWh/gi))add(num(n[2]),850,base+(n.index??0));for(const n of s.matchAll(/(\d{1,3}(?:[.,]\d{3})+(?:[.,]\d+)?)\s*kWh[\s\S]{0,120}?(\d{1,6}[,.]\d{2})\s*(?:€|EUR)/gi)){const q=num(n[1]),a=num(n[2]);if(q&&a)add(a/q*100,620,base+(n.index??0));}}for(const n of t.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi))add(num(n[1]),120,n.index??0);if(!h.length)return emptyField();h.sort((a,b)=>b.score-a.score||a.index-b.index);return field(Math.round(h[0].value*100)/100,h[0].score>=600?"high":"medium");}
function base(t:string):BillAnalysisField{const h:Hit[]=[];for(const m of t.matchAll(/Grundpreis[\s\S]{0,450}/gi)){const s=m[0],baseIndex=m.index??0;for(const n of s.matchAll(/(\d{2,5}[,.]\d{2})\s*(?:€|EUR)\s*(?:\/\s*)?(?:Jahr|a)\b/gi)){const v=num(n[1]);if(v!==null&&v>=20&&v<=3000)h.push({value:v,score:800,index:baseIndex+(n.index??0)});}for(const n of s.matchAll(/(\d{2,5}[,.]\d{2})\s*(?:€|EUR)/gi)){const v=num(n[1]);if(v!==null&&v>=20&&v<=3000)h.push({value:v,score:300,index:baseIndex+(n.index??0)});}}if(!h.length)return emptyField();h.sort((a,b)=>b.score-a.score||a.index-b.index);return field(h[0].value,h[0].score>=800?"high":"medium");}
function payment(t:string):BillAnalysisField{const section=t.match(/(?:Ihre\s+Zahlungen|Zahlungen)[\s\S]{0,1200}/i)?.[0]||"";const hits:number[]=[];for(const n of section.matchAll(/(\d{2,5}(?:[,.]\d{2})?)\s*(?:€|EUR)/g)){const v=num(n[1]);if(v!==null&&v>=20&&v<=5000)hits.push(v);}if(!hits.length)for(const n of t.matchAll(/(?:Abschlag|monatlicher\s+Abschlag)[\s\S]{0,120}(\d{2,5}(?:[,.]\d{2})?)\s*(?:€|EUR)/gi)){const v=num(n[1]);if(v!==null&&v>=20&&v<=5000)hits.push(v);}return field(hits.at(-1)??null,hits.length?"high":"unknown");}
function provider(t:string):BillAnalysisField{const rules:Array<[RegExp,string]>=[[/e\.?\s*o\.?\s*n\b/i,"E.ON"],[/enbw/i,"EnBW"],[/vattenfall/i,"Vattenfall"],[/mainova/i,"Mainova"],[/rheinen?ergie/i,"RheinEnergie"],[/stadtwerke\s+m[uü]nchen/i,"Stadtwerke München"],[/yello/i,"Yello"],[/lichtblick/i,"LichtBlick"],[/naturstrom/i,"Naturstrom"],[/\bewe\b/i,"EWE"],[/enercity/i,"enercity"]];for(const[r,n]of rules)if(r.test(t))return field(n,"high");return emptyField();}
function energy(t:string):BillAnalysisField{const gas=/\bgas\b|gaskosten|gas\s+et/i.test(t),strom=/\bstrom\b|stromkosten|optimalstrom|verbrauchspreis\s+et|strom\s+et/i.test(t);const v=strom&&gas?"Strom + Gas":gas?"Gas":strom?"Strom":null;return field(v,v?"high":"unknown");}
function tariff(t:string):BillAnalysisField{const patterns=[/Ihre\s+Energiekosten\s+E\.ON\s+([^\n]{3,100}?)(?=\s+Zeitraum|\s+Ihre|$)/i,/E\.ON\s+([^\n]{3,100}?(?:Strom|Gas|Plus|Direkt|Tarif)[^\n]{0,50})/i];for(const rx of patterns){const v=t.match(rx)?.[1]?.replace(/\s+/g," ").trim();if(v&&!/^E\.ON$/i.test(v))return field(v,"medium");}return emptyField();}
function parse(t:string):BillAnalysisResult{const x=clean(t),r=emptyBillAnalysis();r.energyType=energy(x);r.provider=provider(x);r.tariffName=tariff(x);r.annualConsumptionKwh=annual(x);r.workPriceCtPerKwh=work(x);r.basePriceEurPerYear=base(x);r.monthlyPaymentEur=payment(x);const ds=dates(x);ds.sort((a,b)=>b.days-a.days);r.billingPeriod=field(ds[0]?.raw??null,ds.length?"high":"unknown");const ce=x.match(/(?:Vertragsende|Vertragslaufzeit\s*bis|Belieferung\s*bis)[\s:]+(\d{1,2}[./]\d{1,2}[.]\d{4})/i);r.contractEnd=field(ce?.[1]?.replace(/\//g,".")??null,ce?"medium":"unknown");const ca=x.match(/k(?:ü|u)ndigungsfrist[\s:]+([^\n]{1,100})/i);r.cancellationPeriod=field(ca?.[1]?.trim()??null,ca?"medium":"unknown");const ad=x.match(/(?:Lieferadresse|Verbrauchsstelle|Anschrift)[\s:]+([^\n]{5,120})/i);r.address=field(ad?.[1]?.trim()??null,ad?"medium":"unknown");return r;}
async function textOf(file:File):Promise<string>{if(file.type!=="application/pdf")return recognizeImage(file);const native=await extractPdfText(file),n=clean(native);const good=/(?:Arbeitspreis|Verbrauchspreis)[\s\S]{0,500}(?:ct\s*\/\s*kWh|cent\s*\/\s*kWh|€\s*\/\s*kWh)/i.test(n)||/\d[\d.,]*\s*kWh/i.test(n);if(native.length>=100&&good)return native;const ocr=await renderPdfForOcr(file);return[native,ocr].filter(Boolean).join("\n");}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{if(typeof window==="undefined")throw new Error("BILL_ANALYSIS_BROWSER_ONLY");const endpoint=process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL;if(endpoint){const body=new FormData();body.append("file",file,file.name);const response=await fetch(endpoint,{method:"POST",body});if(!response.ok)throw new Error(`BILL_ANALYSIS_HTTP_${response.status}`);const data=await response.json();return data.result??data;}return parse(await textOf(file));}
