export type BillAnalysisField={value:string|number|null;confidence:"high"|"medium"|"low"|"unknown";source:"document"|"not_detected"};
export type BillAnalysisResult={energyType:BillAnalysisField;provider:BillAnalysisField;annualConsumptionKwh:BillAnalysisField;workPriceCtPerKwh:BillAnalysisField;basePriceEurPerYear:BillAnalysisField;monthlyPaymentEur:BillAnalysisField;billingPeriod:BillAnalysisField;contractEnd:BillAnalysisField;cancellationPeriod:BillAnalysisField;address:BillAnalysisField};
export const BILL_ANALYSIS_FIELDS:Array<keyof BillAnalysisResult>=["energyType","provider","annualConsumptionKwh","workPriceCtPerKwh","basePriceEurPerYear","monthlyPaymentEur","billingPeriod","contractEnd","cancellationPeriod","address"];
export function emptyBillAnalysis():BillAnalysisResult{const e=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"});return{energyType:e(),provider:e(),annualConsumptionKwh:e(),workPriceCtPerKwh:e(),basePriceEurPerYear:e(),monthlyPaymentEur:e(),billingPeriod:e(),contractEnd:e(),cancellationPeriod:e(),address:e()};}
declare global{interface Window{Tesseract?:any}}
const CDN="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";
const load=(src:string)=>new Promise<void>((ok,no)=>{if(document.querySelector(`script[data-cpm-ocr="${src}"]`))return ok();const s=document.createElement("script");s.src=src;s.async=true;s.dataset.cpmOcr=src;s.onload=()=>ok();s.onerror=()=>no(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(s);});
function canvasFrom(src:unknown){if(typeof document==="undefined")return src;const a=document.createElement("canvas");if(src instanceof HTMLCanvasElement){a.width=src.width;a.height=src.height;a.getContext("2d")!.drawImage(src,0,0);}else if(src instanceof HTMLImageElement){a.width=src.naturalWidth||src.width;a.height=src.naturalHeight||src.height;a.getContext("2d")!.drawImage(src,0,0);}return a;}
function enhance(src:unknown,mode:"color"|"gray"|"threshold"){const a=canvasFrom(src);if(!(a instanceof HTMLCanvasElement))return src;const scale=2.2,b=document.createElement("canvas");b.width=Math.ceil(a.width*scale);b.height=Math.ceil(a.height*scale);const c=b.getContext("2d")!;c.imageSmoothingEnabled=false;c.drawImage(a,0,0,b.width,b.height);if(mode!=="color"){const d=c.getImageData(0,0,b.width,b.height);for(let i=0;i<d.data.length;i+=4){const l=.299*d.data[i]+.587*d.data[i+1]+.114*d.data[i+2];const v=mode==="threshold"?(l<180?0:255):Math.max(0,Math.min(255,(l-128)*1.35+128));d.data[i]=d.data[i+1]=d.data[i+2]=v;}c.putImageData(d,0,0);}return b;}
async function imageCanvas(file:File){return await new Promise<HTMLCanvasElement>((ok,no)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{const c=document.createElement("canvas");c.width=i.naturalWidth||i.width;c.height=i.naturalHeight||i.height;c.getContext("2d")!.drawImage(i,0,0);URL.revokeObjectURL(u);ok(c)};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error("IMAGE_DECODE_FAILED"))};i.src=u;});}
async function recognize(src:unknown){await load(CDN);if(!window.Tesseract)throw new Error("OCR_LIBRARY_LOAD_FAILED");const worker=await window.Tesseract.createWorker("deu");try{const texts:string[]=[];for(const mode of ["color","gray","threshold"] as const){const r=await worker.recognize(enhance(src,mode),{rotateAuto:true},{tessedit_pageseg_mode:"6",preserve_interword_spaces:"1",user_defined_dpi:"300"});const t=r.data.text||"";if(t.trim())texts.push(t);if(/Arbeitspreis|Verbrauchspreis|Grundpreis|Jahresverbrauch|kWh|ct\s*\/?\s*kWh/i.test(t))break;}return texts.join("\n");}finally{await worker.terminate();}}
async function textOf(file:File){if(file.type!=="application/pdf")return recognize(await imageCanvas(file));const imp=new Function("u","return import(u)") as(u:string)=>Promise<any>;const pdfjs=await imp("https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.54/build/pdf.mjs");const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const pages:string[]=[];for(let i=1;i<=Math.min(10,pdf.numPages);i++){const p=await pdf.getPage(i),v=p.getViewport({scale:3}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const x=c.getContext("2d");if(x)await p.render({canvasContext:x,viewport:v}).promise;pages.push(await recognize(c));}return pages.join("\n");}
function clean(t:string){return t.replace(/\u00a0/g," ").replace(/[‐‑‒–—]/g,"-").replace(/\r/g,"").replace(/k\s*[vw]\s*[whn]/gi,"kWh").replace(/kwh|kvvh|kvwh|kwn|kvn/gi,"kWh").replace(/grund[o0]reis|grundpre[i1]s/gi,"Grundpreis").replace(/arbeit\s*(?:s|ss)?\s*pre[i1]s|arbeitspre[il]s/gi,"Arbeitspreis").replace(/verbrauchspre[i1]s/gi,"Verbrauchspreis").replace(/jahresverh?rauch/gi,"Jahresverbrauch").replace(/stromkosten/gi,"Stromkosten").replace(/str[o0]m/gi,"Strom").replace(/e\s*[.]?\s*o\s*n/gi,"E.ON").replace(/c\s*t\s*\/\s*k\s*[vw]\s*[whn]/gi,"ct/kWh").replace(/cent\s*\/\s*kWh/gi,"ct/kWh").replace(/€\s*\/\s*kWh/gi,"€/kWh").replace(/[ \t]+/g," ");}
function num(raw:string){let s=raw.replace(/\s/g,"").replace(/[^0-9,.-]/g,"");if(!s)return null;if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}\.\d{3}$/.test(s))s=s.replace(".","");const v=Number(s);return Number.isFinite(v)?v:null;}
const field=(v:string|number|null,c:BillAnalysisField["confidence"]="medium"):BillAnalysisField=>v===null||v===""?{value:null,confidence:"unknown",source:"not_detected"}:{value:v,confidence:c,source:"document"};
function candidatesInWindow(text:string,rx:RegExp,from:number,to:number){const s=text.slice(from,to);return[...s.matchAll(rx)].map(m=>({value:num(m[1]),index:from+(m.index??0),match:m[0]})).filter((x):x is {value:number;index:number;match:string}=>x.value!==null);}
function annual(t:string){const hits:Array<{v:number;score:number;i:number}>=[];for(const m of t.matchAll(/(?:Jahresverbrauch|Verbrauch\/Menge|Verbrauch\s+im\s+Abrechnungsjahr)[\s\S]{0,500}/gi)){for(const z of candidatesInWindow(m[0],/(\d{1,3}(?:[.,]\d{3})+|\d{4,6})\s*kWh/gi,0,m[0].length)){if(z.value>=300&&z.value<=100000)hits.push({v:z.value,score:260,i:(m.index??0)+z.index});}}for(const z of t.matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d{4,6})\s*kWh/gi)){const v=num(z[1]);if(v!==null&&v>=300&&v<=100000)hits.push({v,score:80,i:z.index??0});}if(!hits.length)return field(null);hits.sort((a,b)=>b.score-a.score||a.i-b.i);return field(hits[0].v,hits[0].score>=200?"high":"medium");}
function work(t:string){const hits:Array<{v:number;score:number;i:number}>=[];const add=(v:number,score:number,i:number)=>{if(v>=5&&v<=60&&Number.isFinite(v))hits.push({v,score,i});};
for(const m of t.matchAll(/(?:Arbeitspreis|Verbrauchspreis|Verbrauchspreis\s+ET)[\s\S]{0,900}/gi)){const s=m[0],base=m.index??0;
for(const z of s.matchAll(/(?:kWh\s*(?:x|×|\*)\s*)?(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)){const v=num(z[1]);if(v!==null)add(v,500,base+(z.index??0));}
for(const z of s.matchAll(/(?:kWh\s*(?:x|×|\*)\s*)?(\d{1,3}[,.]\d{1,3})\s*(?:€|EUR)\s*(?:\/\s*)?kWh/gi)){const v=num(z[1]);if(v!==null)add(v*100,480,base+(z.index??0));}
const q=[...s.matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d{3,6})\s*kWh/gi)].map(z=>num(z[1])).filter((v):v is number=>v!==null&&v>0&&v<100000);
const prices=[...s.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)].map(z=>num(z[1])).filter((v):v is number=>v!==null&&v>=5&&v<=60);if(q.length&&prices.length)add(prices[0],520,base);
for(const z of s.matchAll(/(\d{1,6}(?:[.,]\d{3})?)\s*kWh[\s\S]{0,260}?(\d{1,6}[,.]\d{2})\s*(?:€|EUR)/gi)){const qv=num(z[1]),ev=num(z[2]);if(qv&&ev){const p=ev/qv*100;if(p>=5&&p<=60)add(p,450,base+(z.index??0));}}
}
for(const z of t.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)){const v=num(z[1]);if(v!==null)add(v,120,z.index??0);}
if(!hits.length)return field(null);hits.sort((a,b)=>b.score-a.score||a.i-b.i);return field(Math.round(hits[0].v*100)/100,hits[0].score>=400?"high":"medium");}
function base(t:string){const hits:Array<{v:number;score:number;i:number}>=[];for(const m of t.matchAll(/Grundpreis[\s\S]{0,600}/gi)){const s=m[0],base=m.index??0;for(const z of s.matchAll(/(\d{2,5}[,.]\d{2})\s*(?:€|EUR)\s*(?:\/\s*)?(?:Jahr|a)\b/gi)){const v=num(z[1]);if(v!==null&&v>=20&&v<=3000)hits.push({v,score:400,i:base+(z.index??0)});}for(const z of s.matchAll(/(\d{2,5}[,.]\d{2})\s*(?:€|EUR)/gi)){const v=num(z[1]);if(v!==null&&v>=20&&v<=3000)hits.push({v,score:180,i:base+(z.index??0)});}}if(!hits.length)return field(null);hits.sort((a,b)=>b.score-a.score||a.i-b.i);return field(hits[0].v,hits[0].score>=350?"high":"medium");}
function payment(t:string){const hits:Array<{v:number;i:number}>=[];for(const m of t.matchAll(/(?:Abschlag|monatlich(?:er)?\s+Abschlag|Ihr\s+Abschlag)[\s\S]{0,250}/gi))for(const z of m[0].matchAll(/(\d{2,5}(?:[,.]\d{2})?)\s*(?:€|EUR)/gi)){const v=num(z[1]);if(v!==null&&v>=20&&v<=5000)hits.push({v,i:(m.index??0)+(z.index??0)});}hits.sort((a,b)=>a.i-b.i);return field(hits.at(-1)?.v??null,hits.length?"high":"unknown");}
function period(t:string){const hits:Array<{s:string;days:number}>=[];for(const m of t.matchAll(/(\d{1,2}[./]\d{1,2}[.]\d{4})\s*(?:-|bis)\s*(\d{1,2}[./]\d{1,2}[.]\d{4})/g)){const parse=(s:string)=>{const[d,mo,y]=s.split(/[./]/).map(Number);return new Date(y,mo-1,d).getTime()};hits.push({s:`${m[1].replace(/\//g,".")} - ${m[2].replace(/\//g,".")}`,days:Math.abs(parse(m[2])-parse(m[1]))});}hits.sort((a,b)=>b.days-a.days);return field(hits[0]?.s??null,hits.length?"high":"unknown");}
function provider(t:string){const rules:[RegExp,string][]=[[/e\.?\s*o\.?\s*n\b/i,"E.ON"],[/enbw/i,"EnBW"],[/vattenfall/i,"Vattenfall"],[/mainova/i,"Mainova"],[/\bewe\b/i,"EWE"],[/\binnogy\b/i,"innogy"],[/\benercity\b/i,"enercity"],[/\bswv\b/i,"SWV"]];for(const [rx,name] of rules)if(rx.test(t))return field(name,"high");return field(null);}
function energy(t:string){const st=/\bstrom\b|stromkosten|optimalstrom|verbrauchspreis\s+et|strom\s+et/i.test(t),ga=/\bgas\b|gaskosten|gas\s+et/i.test(t);return field(st&&ga?"Strom + Gas":ga?"Gas":st?"Strom":null,st||ga?"high":"unknown");}
function parse(t:string):BillAnalysisResult{const x=clean(t),r=emptyBillAnalysis();r.energyType=energy(x);r.provider=provider(x);r.annualConsumptionKwh=annual(x);r.workPriceCtPerKwh=work(x);r.basePriceEurPerYear=base(x);r.monthlyPaymentEur=payment(x);r.billingPeriod=period(x);const end=x.match(/(?:Vertragsende|Vertragslaufzeit\s*bis|Belieferung\s*bis)[\s:]+(\d{1,2}[./]\d{1,2}[.]\d{4})/i);r.contractEnd=field(end?.[1]?.replace(/\//g,".")??null,end?"medium":"unknown");const ca=x.match(/k(?:ü|u)ndigungsfrist[\s:]+([^\n]{1,100})/i);r.cancellationPeriod=field(ca?.[1]?.trim()??null,ca?"medium":"unknown");return r;}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{if(typeof window==="undefined")throw new Error("BILL_ANALYSIS_BROWSER_ONLY");const endpoint=process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL;if(endpoint){const body=new FormData();body.append("file",file,file.name);const res=await fetch(endpoint,{method:"POST",body});if(!res.ok)throw new Error(`BILL_ANALYSIS_HTTP_${res.status}`);const data=await res.json();return data.result??data;}return parse(await textOf(file));}
