export type BillAnalysisField = { value: string | number | null; confidence: "high" | "medium" | "low" | "unknown"; source: "document" | "not_detected" };
export type BillAnalysisResult = { energyType: BillAnalysisField; provider: BillAnalysisField; annualConsumptionKwh: BillAnalysisField; workPriceCtPerKwh: BillAnalysisField; basePriceEurPerYear: BillAnalysisField; monthlyPaymentEur: BillAnalysisField; billingPeriod: BillAnalysisField; contractEnd: BillAnalysisField; cancellationPeriod: BillAnalysisField; address: BillAnalysisField };
export const BILL_ANALYSIS_FIELDS: Array<keyof BillAnalysisResult> = ["energyType","provider","annualConsumptionKwh","workPriceCtPerKwh","basePriceEurPerYear","monthlyPaymentEur","billingPeriod","contractEnd","cancellationPeriod","address"];
export function emptyBillAnalysis(): BillAnalysisResult { const e=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"}); return {energyType:e(),provider:e(),annualConsumptionKwh:e(),workPriceCtPerKwh:e(),basePriceEurPerYear:e(),monthlyPaymentEur:e(),billingPeriod:e(),contractEnd:e(),cancellationPeriod:e(),address:e()}; }
declare global { interface Window { Tesseract?: any; } }
function loadScript(src:string):Promise<void>{return new Promise((resolve,reject)=>{if(document.querySelector(`script[data-cpm-src="${src}"]`))return resolve();const s=document.createElement("script");s.src=src;s.async=true;s.dataset.cpmSrc=src;s.onload=()=>resolve();s.onerror=()=>reject(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(s);});}
function preprocessImage(source:unknown,variant:number):HTMLCanvasElement|unknown{if(typeof document==="undefined")return source;const src=document.createElement("canvas");if(source instanceof HTMLCanvasElement){src.width=source.width;src.height=source.height;src.getContext("2d")!.drawImage(source,0,0);}else if(source instanceof HTMLImageElement){src.width=source.naturalWidth||source.width;src.height=source.naturalHeight||source.height;src.getContext("2d")!.drawImage(source,0,0);}else return source;const out=document.createElement("canvas");const scale=variant===0?1.5:2;out.width=Math.ceil(src.width*scale);out.height=Math.ceil(src.height*scale);const ctx=out.getContext("2d");if(!ctx)return source;ctx.imageSmoothingEnabled=false;ctx.drawImage(src,0,0,out.width,out.height);if(variant>0){const data=ctx.getImageData(0,0,out.width,out.height),d=data.data;for(let i=0;i<d.length;i+=4){const lum=.299*d[i]+.587*d[i+1]+.114*d[i+2];const v=variant===1?Math.max(0,Math.min(255,(lum-128)*2+128)):lum<185?0:255;d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(data,0,0);}return out;}
async function ocrImage(image:unknown):Promise<string>{await loadScript("https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js");if(!window.Tesseract)throw new Error("OCR_LIBRARY_LOAD_FAILED");const w=await window.Tesseract.createWorker("deu");try{const out:string[]=[];for(const variant of [0,1,2]){const prepared=preprocessImage(image,variant);for(const mode of ["3","6","11"]){await w.setParameters({tessedit_pageseg_mode:mode,preserve_interword_spaces:"1",user_defined_dpi:"300"});const x=await w.recognize(prepared);if(x.data.text)out.push(x.data.text);}}return out.join("\n");}finally{await w.terminate();}}
async function extractText(file:File):Promise<string>{if(file.type!=="application/pdf")return ocrImage(file);const importer=new Function("url","return import(url)") as (url:string)=>Promise<any>;const pdfjs=await importer("https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.54/build/pdf.mjs");const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const chunks:string[]=[];for(let i=1;i<=Math.min(pdf.numPages,8);i++){const p=await pdf.getPage(i),v=p.getViewport({scale:3.2}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const ctx=c.getContext("2d");if(!ctx)continue;await p.render({canvasContext:ctx,viewport:v}).promise;chunks.push(await ocrImage(c));}return chunks.join("\n");}
function normalizeOcr(t:string):string{return t.replace(/\u00a0/g," ").replace(/\r/g,"").replace(/[|]/g," ").replace(/[€]/g," € ").replace(/[‐‑‒–—]/g,"-").replace(/\bCts?\b/gi,"ct").replace(/kwh/gi,"kWh").replace(/grund[o0]reis/gi,"Grundpreis").replace(/arbeit[s]?preis/gi,"Arbeitspreis").replace(/jahresverbrauch/gi,"Jahresverbrauch").replace(/stromkosten/gi,"Stromkosten").replace(/str[o0]m/gi,"Strom").replace(/\s+/g," ");}
function deNumber(value:string,context?:"currency"|"consumption"|"price"):number|null{let s=value.replace(/\s/g,"").replace(/€/g,"").replace(/[^0-9,.-]/g,"");if(!s)return null;if(context==="currency"&&/^\d{4,5}$/.test(s)){const n=Number(s);if(n>=1000&&n<=999999)return n/100;}if(s.includes(",")){const n=Number(s.replace(/\./g,"").replace(",","."));return Number.isFinite(n)?n:null;}if(context==="consumption"&&/^\d{1,3}(?:\.\d{3})+$/.test(s)){const n=Number(s.replace(/\./g,""));return Number.isFinite(n)?n:null;}const n=Number(s.replace(/,/g,""));return Number.isFinite(n)?n:null;}
function makeField(value:string|number|null,confidence:BillAnalysisField["confidence"]="medium"):BillAnalysisField{return value===null||value===""?{value:null,confidence:"unknown",source:"not_detected"}:{value,confidence,source:"document"};}
function firstDateRange(t:string):string|null{const m=t.match(/(\d{1,2}[.\/]\d{1,2}[.\/]\d{4})\s*(?:-|–|bis)\s*(\d{1,2}[.\/]\d{1,2}[.\/]\d{4})/i);return m?`${m[1].replace(/\//g,".")} - ${m[2].replace(/\//g,".")}`:null;}
function parseAnnualConsumption(clean:string,normalized:string):BillAnalysisField{const patterns=[/(?:Jahresverbrauch|Jahresverbrauchs?wert)[^\d]{0,350}(\d{1,3}(?:\.\d{3})+(?:,\d+)?|\d{4,6}(?:,\d+)?)\s*kWh/i,/(?:auf|für)\s+365\s*Tage[^\d]{0,350}(\d{1,3}(?:\.\d{3})+(?:,\d+)?|\d{4,6}(?:,\d+)?)\s*kWh/i,/(?:365\s*Tage|hochgerechnet|umgerechnet)[\s\S]{0,800}?(\d{1,3}(?:\.\d{3})+(?:,\d+)?|\d{4,6}(?:,\d+)?)\s*kWh/i];for(const p of patterns){const m=clean.match(p);if(m?.[1]){const v=deNumber(m[1],"consumption");if(v!==null&&v>=500&&v<=100000)return makeField(v,"high");}}const marker=normalized.search(/Jahresverbrauch\s+in\s+kWh|365\s+Tage\s+umgerechnet/i);if(marker>=0){const c=normalized.slice(marker,marker+1600);const vals=[...c.matchAll(/(\d{1,3}(?:\.\d{3})+(?:,\d+)?|\d{4,6}(?:,\d+)?)\s*kWh/gi)].map(m=>deNumber(m[1],"consumption")).filter((v):v is number=>v!==null&&v>=500&&v<=100000);if(vals.length){const nonComparison=vals.filter(v=>v!==18388);return makeField(nonComparison[0]??vals[0],"high");}}return makeField(null);}
function findWorkPrice(t:string):number|null{for(const m of t.matchAll(/arbeitspreis[\s\S]{0,240}/gi)){const s=m[0];const vals=[...s.matchAll(/(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\s*\/?\s*kWh/gi)].map(x=>deNumber(x[1],"price")).filter((v):v is number=>v!==null&&v>=5&&v<=60);if(vals.length)return vals[0];}const vals=[...t.matchAll(/(\d{1,3}(?:[.,]\d{1,3})?)\s*ct\s*\/?\s*kWh/gi)].map(x=>deNumber(x[1],"price")).filter((v):v is number=>v!==null&&v>=5&&v<=60);return vals.length?vals[vals.length-1]:null;}
function findBasePrice(t:string):number|null{for(const m of t.matchAll(/grundpreis[\s\S]{0,240}/gi)){const s=m[0];for(const x of s.matchAll(/(\d{1,5}(?:[.,]\d{1,2})?|\d{4,5})\s*€\s*\/?\s*(?:jahr|a)\b/gi)){const v=deNumber(x[1],"currency");if(v!==null&&v>=20&&v<=2000)return v;}for(const x of s.matchAll(/(\d{1,5}(?:[.,]\d{1,2})?|\d{4,5})\s*€/g)){const v=deNumber(x[1],"currency");if(v!==null&&v>=20&&v<=2000)return v;}}return null;}
function findPayment(t:string):number|null{for(const p of [/(?:aktueller|aktuelle|monatlicher|monatliche)\s+abschlag[\s\S]{0,120}?(\d{1,4}(?:[.,]\d{2})?)\s*€/i,/abschlag\s+(?:von|:)?\s*(\d{1,4}(?:[.,]\d{2})?)\s*€/i]){const m=t.match(p);if(m?.[1]){const v=deNumber(m[1],"currency");if(v!==null&&v>=10&&v<=2000)return v;}}return null;}
function parseText(text:string):BillAnalysisResult{const r=emptyBillAnalysis();const clean=text.replace(/\u00a0/g," ").replace(/\r/g,"");const n=normalizeOcr(clean);const hasStrom=/\bstrom\b/i.test(n)||/stromkosten/i.test(n)||/e\.on[\s\S]{0,100}strom/i.test(n);const hasGas=/\bgas\b/i.test(n)||/gaskosten/i.test(n);r.energyType=makeField(hasStrom&&hasGas?"Strom + Gas":hasGas?"Gas":hasStrom?"Strom":null,hasStrom||hasGas?"high":"unknown");const provider=/e\s*\.?\s*on/i.test(n)||/\beon\b/i.test(n)?"E.ON":/\benbw\b/i.test(n)?"EnBW":/\bvattenfall\b/i.test(n)?"Vattenfall":/\bmainova\b/i.test(n)?"Mainova":/\bewe\b/i.test(n)?"EWE":null;r.provider=makeField(provider,provider?"high":"unknown");r.annualConsumptionKwh=parseAnnualConsumption(clean,n);const wp=findWorkPrice(n);r.workPriceCtPerKwh=makeField(wp,wp!==null?"high":"unknown");const bp=findBasePrice(n);r.basePriceEurPerYear=makeField(bp,bp!==null?"high":"unknown");const pay=findPayment(n);r.monthlyPaymentEur=makeField(pay,pay!==null?"high":"unknown");const period=firstDateRange(clean);r.billingPeriod=makeField(period,period?"high":"unknown");const end=clean.match(/(?:vertragsende|vertragslaufzeit\s*bis|belieferung\s*bis)[\s:]+(\d{1,2}[.\/]\d{1,2}[.\/]\d{4})/i);r.contractEnd=makeField(end?.[1]?.replace(/\//g,".")||null,end?"medium":"unknown");const cancel=clean.match(/k(?:ü|u)ndigungsfrist[\s:]+([^\n]{1,80})/i);r.cancellationPeriod=makeField(cancel?.[1]?.trim()||null,cancel?"medium":"unknown");const address=clean.match(/(?:anschrift|lieferanschrift|verbrauchsstelle)[\s:]+([^\n]{5,120})/i);r.address=makeField(address?.[1]?.trim()||null,address?"medium":"unknown");return r;}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{if(typeof window==="undefined")throw new Error("BILL_ANALYSIS_BROWSER_ONLY");const endpoint=process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL;if(endpoint){const body=new FormData();body.append("file",file,file.name);const response=await fetch(endpoint,{method:"POST",body});if(!response.ok)throw new Error("BILL_ANALYSIS_FAILED");return(await response.json()) as BillAnalysisResult;}const text=await extractText(file);if(!text.trim())throw new Error("BILL_TEXT_NOT_RECOGNIZED");return parseText(text);}
