export type BillAnalysisField={value:string|number|null;confidence:"high"|"medium"|"low"|"unknown";source:"document"|"not_detected"};
export type BillAnalysisResult={energyType:BillAnalysisField;provider:BillAnalysisField;annualConsumptionKwh:BillAnalysisField;workPriceCtPerKwh:BillAnalysisField;basePriceEurPerYear:BillAnalysisField;monthlyPaymentEur:BillAnalysisField;billingPeriod:BillAnalysisField;contractEnd:BillAnalysisField;cancellationPeriod:BillAnalysisField;address:BillAnalysisField};
export const BILL_ANALYSIS_FIELDS:Array<keyof BillAnalysisResult>=["energyType","provider","annualConsumptionKwh","workPriceCtPerKwh","basePriceEurPerYear","monthlyPaymentEur","billingPeriod","contractEnd","cancellationPeriod","address"];
export function emptyBillAnalysis():BillAnalysisResult{const e=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"});return{energyType:e(),provider:e(),annualConsumptionKwh:e(),workPriceCtPerKwh:e(),basePriceEurPerYear:e(),monthlyPaymentEur:e(),billingPeriod:e(),contractEnd:e(),cancellationPeriod:e(),address:e()};}
declare global{interface Window{Tesseract?:any}}
const script=(src:string)=>new Promise<void>((ok,no)=>{if(document.querySelector(`script[data-cpm="${src}"]`))return ok();const s=document.createElement("script");s.src=src;s.async=true;s.dataset.cpm=src;s.onload=()=>ok();s.onerror=()=>no(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(s);});
async function imageCanvas(src:File){return await new Promise<HTMLCanvasElement>((ok,no)=>{const u=URL.createObjectURL(src),i=new Image();i.onload=()=>{const c=document.createElement("canvas");c.width=i.naturalWidth||i.width;c.height=i.naturalHeight||i.height;c.getContext("2d")!.drawImage(i,0,0);URL.revokeObjectURL(u);ok(c)};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error("IMAGE_DECODE_FAILED"))};i.src=u;});}
function prep(src:unknown,v:number){if(typeof document==="undefined")return src;const a=document.createElement("canvas");if(src instanceof HTMLCanvasElement){a.width=src.width;a.height=src.height;a.getContext("2d")!.drawImage(src,0,0);}else if(src instanceof HTMLImageElement){a.width=src.naturalWidth||src.width;a.height=src.naturalHeight||src.height;a.getContext("2d")!.drawImage(src,0,0);}else return src;const scale=v?2:1.5,b=document.createElement("canvas");b.width=Math.ceil(a.width*scale);b.height=Math.ceil(a.height*scale);const c=b.getContext("2d")!;c.imageSmoothingEnabled=false;c.drawImage(a,0,0,b.width,b.height);if(v){const d=c.getImageData(0,0,b.width,b.height);for(let i=0;i<d.data.length;i+=4){const l=.299*d.data[i]+.587*d.data[i+1]+.114*d.data[i+2];const x=v===1?Math.max(0,Math.min(255,(l-128)*2+128)):l<180?0:255;d.data[i]=d.data[i+1]=d.data[i+2]=x;}c.putImageData(d,0,0);}return b;}
async function ocr(img:unknown){await script("https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js");if(!window.Tesseract)throw new Error("OCR_LIBRARY_LOAD_FAILED");const w=await window.Tesseract.createWorker("deu");try{const a:string[]=[];for(const v of [0,1,2])for(const mode of ["3","6","11"]){const r=await w.recognize(prep(img,v),{rotateAuto:true},{tessedit_pageseg_mode:mode,preserve_interword_spaces:"1",user_defined_dpi:"300"});if(r.data.text)a.push(r.data.text);}return a.join("\n");}finally{await w.terminate();}}
async function textOf(f:File){if(f.type!=="application/pdf")return ocr(await imageCanvas(f));const imp=new Function("u","return import(u)") as(u:string)=>Promise<any>;const pdfjs=await imp("https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.54/build/pdf.mjs");const pdf=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;const out:string[]=[];for(let i=1;i<=Math.min(8,pdf.numPages);i++){const p=await pdf.getPage(i),v=p.getViewport({scale:3.2}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const x=c.getContext("2d");if(x)await p.render({canvasContext:x,viewport:v}).promise;out.push(await ocr(c));}return out.join("\n");}
function norm(t:string){return t.replace(/\u00a0/g," ").replace(/\r/g,"").replace(/[|]/g," ").replace(/[‐‑‒–—]/g,"-").replace(/k\s*w\s*h/gi,"kWh").replace(/kwh/gi,"kWh").replace(/grund[o0]reis|grundpre[i1]s/gi,"Grundpreis").replace(/arbeit\s*[s]?\s*pre[i1]s|arbeitspre[il]s/gi,"Arbeitspreis").replace(/jahresverh?rauch|jahresverhrauch/gi,"Jahresverbrauch").replace(/stromkosten/gi,"Stromkosten").replace(/str[o0]m/gi,"Strom").replace(/e\s*[.]?\s*o\s*n/gi,"E.ON").replace(/e\s*t\s*\/\s*k\s*w\s*h/gi,"ct/kWh").replace(/c\s*t\s*\/\s*k\s*w\s*h/gi,"ct/kWh").replace(/eurocent|cent\s*\/\s*kWh/gi,"ct/kWh").replace(/ct\s*\/\s*kWh/gi,"ct/kWh").replace(/€\s*\/\s*kWh/gi,"€/kWh").replace(/€/g," € ").replace(/[ \t]+/g," ");}
function n(s:string,k:"money"|"consumption"|"price"="money"){let x=s.replace(/\s|€/g,"").replace(/[^0-9,.-]/g,"");if(!x)return null;if(x.includes(","))x=x.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}\.\d{3}$/.test(x))x=x.replace(".","");const z=Number(x);return Number.isFinite(z)?z:null;}
const fld=(v:string|number|null,c:BillAnalysisField["confidence"]="medium"):BillAnalysisField=>v===null||v===""?{value:null,confidence:"unknown",source:"not_detected"}:{value:v,confidence:c,source:"document"};
function nums(s:string,rx:RegExp,k:"money"|"consumption"|"price"){return[...s.matchAll(rx)].map(m=>n(m[1],k)).filter((x):x is number=>x!==null);}
function annual(t:string):BillAnalysisField{const clean=t.replace(/\s+/g," ");const candidates:Array<{v:number;score:number;index:number}>=[];const add=(v:number,score:number,index:number)=>{if(v>=500&&v<=100000&&!/^\d+$/.test(String(v))||v>=500&&v<=100000)candidates.push({v,score,index});};
for(const m of clean.matchAll(/Ihr\s+Jahresverbrauch[^]{0,900}/gi)){const c=m[0],base=m.index??0;for(const z of c.matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d{4,6})\s*kWh/gi)){const v=n(z[1],"consumption");if(v!==null&&v>=500&&v<=100000){const raw=z[1].replace(/\s/g,"");const round=/^\d+[.]?0{3}$/.test(raw)||/^\d{4,6}$/.test(raw)&&v%5000===0;add(v,round?30:180,base+(z.index??0));}}
for(const z of c.matchAll(/\b(\d{1,3}\.\d{3}|\d{5,6})\b/g)){const v=n(z[1],"consumption");if(v!==null&&v>=500&&v<=100000){const raw=z[1];const round=/^\d+[.]?0{3}$/.test(raw)||v%5000===0;add(v,round?25:170,base+(z.index??0));}}}
if(!candidates.length)for(const m of clean.matchAll(/auf\s+365\s*Tage\s+umgerechnet[^]{0,500}/gi)){for(const z of m[0].matchAll(/\b(\d{1,3}\.\d{3}|\d{5,6})\b/g)){const v=n(z[1],"consumption");if(v!==null&&v>=500&&v<=100000&&v%5000!==0)add(v,100,m.index??0);}}
if(!candidates.length)return fld(null);candidates.sort((a,b)=>b.score-a.score||a.index-b.index);return fld(candidates[0].v,candidates[0].score>=150?"high":"medium");}
function work(t:string):BillAnalysisField{const clean=t.replace(/\s+/g," ");const candidates:Array<{v:number;score:number;index:number}>=[];const add=(v:number,score:number,index:number)=>{if(v>=5&&v<=60)candidates.push({v,score,index});};
for(const m of clean.matchAll(/Arbeitspreis/gi)){const i=m.index??0,c=clean.slice(i,Math.min(clean.length,i+1800));for(const z of c.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)){const v=n(z[1],"price");if(v!==null)add(v,170,i+z.index!);}for(const z of c.matchAll(/(\d{1,3}[,.]\d{1,3})\s*(?:€|EUR)\s*(?:\/\s*)?kWh/gi)){const v=n(z[1],"price");if(v!==null)add(v*100,165,i+z.index!);}for(const z of c.matchAll(/(\d{1,6}(?:[.,]\d{3})?)\s*kWh[^]{0,180}?(\d{1,3}[,.]\d{1,2})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)){const q=n(z[1],"consumption"),p=n(z[2],"price");if(q&&p)add(p,190,i+z.index!);}for(const z of c.matchAll(/(\d{1,6}(?:[.,]\d{3})?)\s*kWh[^]{0,260}?(\d{1,6}[,.]\d{2})\s*€/gi)){const q=n(z[1],"consumption"),e=n(z[2],"money");if(q&&e){const p=e/q*100;if(p>=5&&p<=60)add(p,230,i+z.index!);}}}
for(const z of clean.matchAll(/(\d{1,6}(?:[.,]\d{3})?)\s*kWh[^]{0,260}?(\d{1,6}[,.]\d{2})\s*€/gi)){const q=n(z[1],"consumption"),e=n(z[2],"money");if(q&&e){const p=e/q*100;if(p>=5&&p<=60)add(p,70,z.index??0);}}
if(!candidates.length)for(const z of clean.matchAll(/(\d{1,3}[,.]\d{1,2})\s*(?:ct|c|cent)\s*(?:\/\s*)?kWh/gi)){const v=n(z[1],"price");if(v!==null)add(v,50,z.index??0);}
if(!candidates.length)return fld(null);candidates.sort((a,b)=>b.score-a.score||a.index-b.index);return fld(Math.round(candidates[0].v*100)/100,candidates[0].score>=150?"high":"medium");}
function base(t:string):BillAnalysisField{const clean=t.replace(/\s+/g," ");const candidates:Array<{v:number;score:number;index:number}>=[];const add=(v:number,score:number,index:number)=>{if(v>=20&&v<=2000)candidates.push({v,score,index});};
for(const h of clean.matchAll(/Grundpreis/gi)){const i=h.index??0,c=clean.slice(i,Math.min(clean.length,i+1000));for(const z of c.matchAll(/(\d{2,5}[,.]\d{2})\s*€\s*(?:\/?\s*)?(?:Jahr|a)\b/gi)){const v=n(z[1],"money");if(v!==null)add(v,220,i+z.index!);}for(const z of c.matchAll(/(\d{1,5}[,.]\d{2})\s*€\s*\/?\s*(?:Jahr|a)/gi)){const v=n(z[1],"money");if(v!==null)add(v,220,i+z.index!);}const days=nums(c,/(\d{1,3})\s*Tage/gi,"consumption").filter(x=>x>=1&&x<=400);if(days.length){for(const z of c.matchAll(/(\d{2,5}[,.]\d{2})\s*€/g)){const e=n(z[1],"money");if(e!==null&&e>=10&&e<1000){const v=e/days[0]*365;if(v>=20&&v<=2000)add(Math.round(v*100)/100,150,i+z.index!);}}}}
if(!candidates.length)return fld(null);candidates.sort((a,b)=>b.score-a.score||a.index-b.index);return fld(candidates[0].v,candidates[0].score>=200?"high":"medium");}
function pay(t:string):BillAnalysisField{const a:number[]=[];for(const m of t.matchAll(/abschlag[\s\S]{0,250}/gi))a.push(...nums(m[0],/(\d{2,4}(?:[.,]\d{2})?)\s*€/g,"money").filter(x=>x>=50&&x<=2000));return fld(a.at(-1)??null,a.length?"high":"unknown");}
function periods(t:string){const a:Array<{s:string;d:number}>=[];for(const m of t.matchAll(/(\d{1,2}[.\/]\d{1,2}[.]\d{4})\s*(?:-|bis)\s*(\d{1,2}[.\/]\d{1,2}[.]\d{4})/gi)){const f=(x:string)=>{const[d,mo,y]=x.split(/[.\/]/).map(Number);return new Date(y,mo-1,d).getTime()};a.push({s:`${m[1].replace(/\//g,".")} - ${m[2].replace(/\//g,".")}`,d:Math.abs(f(m[2])-f(m[1]))});}return a;}
function parse(t:string):BillAnalysisResult{const r=emptyBillAnalysis(),x=norm(t),st=/\bstrom\b|stromkosten|optimalstrom/i.test(x),ga=/\bgas\b|gaskosten/i.test(x);r.energyType=fld(st&&ga?"Strom + Gas":ga?"Gas":st?"Strom":null,st||ga?"high":"unknown");const p=/e\.on|eon/i.test(x)?"E.ON":/\benbw\b/i.test(x)?"EnBW":/\bvattenfall\b/i.test(x)?"Vattenfall":/\bmainova\b/i.test(x)?"Mainova":/\bewe\b/i.test(x)?"EWE":null;r.provider=fld(p,p?"high":"unknown");r.annualConsumptionKwh=annual(x);r.workPriceCtPerKwh=work(x);r.basePriceEurPerYear=base(x);r.monthlyPaymentEur=pay(x);const ps=periods(t).sort((a,b)=>b.d-a.d);r.billingPeriod=fld(ps[0]?.s||null,ps.length?"high":"unknown");const end=t.match(/(?:vertragsende|vertragslaufzeit\s*bis|belieferung\s*bis)[\s:]+(\d{1,2}[.\/]\d{1,2}[.]\d{4})/i);r.contractEnd=fld(end?.[1]?.replace(/\//g,".")||null,end?"medium":"unknown");const ca=t.match(/k(?:ü|u)ndigungsfrist[\s:]+([^\n]{1,80})/i);r.cancellationPeriod=fld(ca?.[1]?.trim()||null,ca?"medium":"unknown");const ad=t.match(/(?:anschrift|lieferanschrift|verbrauchsstelle)[\s:]+([^\n]{5,120})/i);r.address=fld(ad?.[1]?.trim()||null,ad?"medium":"unknown");return r;}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{if(typeof window==="undefined")throw new Error("BILL_ANALYSIS_BROWSER_ONLY");const endpoint=process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL;if(endpoint){const b=new FormData();b.append("file",file,file.name);const q=await fetch(endpoint,{method:"POST",body:b});if(!q.ok)throw new Error("BILL_ANALYSIS_FAILED");return await q.json();}const t=await textOf(file);if(!t.trim())throw new Error("BILL_TEXT_NOT_RECOGNIZED");return parse(t);}
