export type BillAnalysisField={value:string|number|null;confidence:"high"|"medium"|"low"|"unknown";source:"document"|"not_detected"};
export type BillAnalysisResult={energyType:BillAnalysisField;provider:BillAnalysisField;tariffName:BillAnalysisField;annualConsumptionKwh:BillAnalysisField;workPriceCtPerKwh:BillAnalysisField;basePriceEurPerYear:BillAnalysisField;monthlyPaymentEur:BillAnalysisField;billingPeriod:BillAnalysisField;contractEnd:BillAnalysisField;cancellationPeriod:BillAnalysisField;address:BillAnalysisField};
const empty=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"});
const f=(v:string|number|null,c:BillAnalysisField["confidence"]="medium"):BillAnalysisField=>v===null||v===""?empty():{value:v,confidence:c,source:"document"};
const fields=(Object.keys({energyType:0,provider:0,tariffName:0,annualConsumptionKwh:0,workPriceCtPerKwh:0,basePriceEurPerYear:0,monthlyPaymentEur:0,billingPeriod:0,contractEnd:0,cancellationPeriod:0,address:0}) as Array<keyof BillAnalysisResult>);
export function emptyBillAnalysis():BillAnalysisResult{return Object.fromEntries(fields.map(k=>[k,empty()])) as BillAnalysisResult;}
declare global{interface Window{Tesseract?:any}}
const OCR="https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/5.1.1/tesseract.min.js",WORKER="https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/5.1.1/worker.min.js",LANG="https://tessdata.projectnaptha.com/4.0.0",CORE="https://cdn.jsdelivr.net/npm/tesseract.js-core@5.1.0",PDF="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.54/pdf.min.mjs",PDFW="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.54/pdf.worker.min.mjs";
let ocrP:Promise<void>|null=null,pdfP:Promise<any>|null=null;
function loadOcr(){if(typeof document==="undefined")return Promise.reject(new Error("OCR_UNAVAILABLE"));if(window.Tesseract)return Promise.resolve();if(ocrP)return ocrP;ocrP=new Promise((ok,no)=>{const s=document.createElement("script");s.src=OCR;s.async=true;s.onload=()=>ok();s.onerror=()=>no(new Error("OCR_LOAD_FAILED"));document.head.appendChild(s)}).catch(e=>{ocrP=null;throw e});return ocrP}
async function pdfjs(){if(pdfP)return pdfP;const imp=new Function("u","return import(u)") as (u:string)=>Promise<any>;pdfP=imp(PDF).then(m=>{m.GlobalWorkerOptions.workerSrc=PDFW;return m}).catch(e=>{pdfP=null;throw e});return pdfP}
function timeout<T>(p:Promise<T>,ms:number){return Promise.race([p,new Promise<T>((_,r)=>setTimeout(()=>r(new Error("TIMEOUT")),ms))])}
function norm(t:string){return t.replace(/\u00a0/g," ").replace(/[‐‑‒–—]/g,"-").replace(/[|]/g," ").replace(/\r/g,"\n").replace(/k\s*[wvw]\s*h/gi,"kWh").replace(/kw[hH]/g,"kWh").replace(/grund[o0]reis|grundpre[i1]s|grundoeis/gi,"Grundpreis").replace(/arbeit\s*(?:s|ss)?\s*pre[i1]s|arbeitspre[il]s|ar[bp]atspre[i1]s/gi,"Arbeitspreis").replace(/verbrauch\s*spre[i1]s|verbrauchspre[il]s/gi,"Verbrauchspreis").replace(/jahresverh?rauch|jahresverhrauch/gi,"Jahresverbrauch").replace(/str[o0]m/gi,"Strom").replace(/g[a4]s/gi,"Gas").replace(/cent\s*\/\s*kwh/gi,"ct/kWh").replace(/c\s*t\s*\/\s*kwh/gi,"ct/kWh").replace(/[ \t]+/g," ")}
function num(s:string){let x=s.replace(/\s/g,"").replace(/[^0-9,.-]/g,"");if(!x)return null;const c=x.lastIndexOf(","),d=x.lastIndexOf(".");if(c>=0&&d>=0)x=c>d?x.replace(/\./g,"").replace(",","."):x.replace(/,/g,"");else if(c>=0)x=x.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}\.\d{3}$/.test(x))x=x.replace(".","");const n=Number(x);return Number.isFinite(n)?n:null}
function firstNumber(t:string,patterns:RegExp[],min:number,max:number){for(const p of patterns){const m=t.match(p);if(!m)continue;const n=num(m[1]);if(n!==null&&n>=min&&n<=max)return n}return null}
function energy(t:string){const gas=/\bGas\b|Erdgas|Gasverbrauch|Gasrechnung|Gaskosten|Gaslieferung/i.test(t);const strom=/\bStrom\b|Elektrizität|Stromverbrauch|Stromrechnung|Stromkosten|Netznutzung Strom/i.test(t);return f(gas&&strom?"Strom + Gas":gas?"Gas":strom?"Strom":null,gas||strom?"high":"unknown")}
function provider(t:string){const names=["ENTEGA","E.ON","goldgas","EnBW","Vattenfall","Mainova","RheinEnergie","Yello","LichtBlick","Naturstrom","eprimo","EWE","enercity","Süwag","MVV Energie","lekker Energie","Octopus Energy","Tibber","EWR","ESWE Versorgung"];for(const n of names)if(new RegExp(n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i").test(t))return f(n,"high");return empty()}
function tariff(t:string){for(const p of [/(?:Tarifname|Produktname)\s*[:\-]?\s*([^\n]{3,100})/i,/(?:Tarif|Produkt|Stromtarif|Gastarif)\s*[:\-]?\s*([^\n]{3,100})/i]){const m=t.match(p);if(m?.[1]){let v=m[1].trim().replace(/\s{2,}/g," ").replace(/(?:Jahresverbrauch|Arbeitspreis|Grundpreis).*$/i,"").trim();if(v.length>=3)return f(v,"medium")}}return empty()}
function annual(t:string){const pats=[/(?:Jahresverbrauch|Jahresverbrauch\s+(?:Strom|Gas)|Gesamtverbrauch|Verbrauch\s+gesamt|Ihr\s+Verbrauch|Abgerechneter\s+Verbrauch)[^\n]{0,120}?([0-9][0-9., ]{2,})\s*kWh/i,/(?:Verbrauch|Menge)[^\n]{0,80}?([0-9][0-9., ]{2,})\s*kWh/i];const n=firstNumber(t,pats,300,10000000);return f(n,n!==null?"high":"unknown")}
function work(t:string){const n=firstNumber(t,[/(?:Arbeitspreis|Verbrauchspreis)[^\n]{0,100}?([0-9]{1,3}[,.][0-9]{1,3})\s*(?:ct|cent)\s*(?:\/|pro)\s*kWh/i,/([0-9]{1,3}[,.][0-9]{1,3})\s*ct\/kWh/i],5,100);return f(n===null?null:Math.round(n*100)/100,n!==null?"high":"unknown")}
function base(t:string){const y=firstNumber(t,[/Grundpreis[^\n]{0,100}?([0-9]{1,5}[,.][0-9]{1,2})\s*(?:€|EUR)\s*(?:\/\s*Jahr|pro\s+Jahr|jährlich)/i],10,10000);if(y!==null)return f(Math.round(y*100)/100,"high");const m=firstNumber(t,[/Grundpreis[^\n]{0,100}?([0-9]{1,5}[,.][0-9]{1,2})\s*(?:€|EUR)\s*(?:\/\s*Monat|pro\s+Monat|monatlich)/i],1,1000);return f(m===null?null:Math.round(m*12*100)/100,m!==null?"high":"unknown")}
function monthly(t:string){const n=firstNumber(t,[/(?:monatlicher\s+Abschlag|neuer\s+Abschlag|Abschlagszahlung|Abschlag)[^\n]{0,100}?([0-9]{2,5}[,.][0-9]{1,2})\s*(?:€|EUR)/i],10,10000);return f(n,n!==null?"high":"unknown")}
function date(s:string){return s.replace(/\//g,".")}
function period(t:string){const m=t.match(/(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})\s*(?:-|bis|–)\s*(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})/);return f(m?`${date(m[1])} - ${date(m[2])}`:null,m?"high":"unknown")}
function contract(t:string){const m=t.match(/(?:Vertragsende|Vertrag(?:slaufzeit)?\s*(?:bis|endet)|Mindestvertragslaufzeit)[^\n]{0,100}?(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})/i);return f(m?.[1]?date(m[1]):null,m?"high":"unknown")}
function cancel(t:string){const m=t.match(/(?:Kündigungsfrist|kündbar)[^\n]{0,100}?([0-9]{1,3}\s*(?:Tage?|Wochen?|Monate?))/i);return f(m?.[1]||null,m?"high":"unknown")}
function address(t:string){const m=t.match(/(?:Lieferadresse|Verbrauchsstelle|Entnahmestelle|Lieferstelle|Anschrift)\s*[:\-]?\s*([^\n]{5,140})/i);return f(m?.[1]?.trim()||null,m?"medium":"unknown")}
export function parseBillText(raw:string):BillAnalysisResult{const t=norm(raw);return{energyType:energy(t),provider:provider(t),tariffName:tariff(t),annualConsumptionKwh:annual(t),workPriceCtPerKwh:work(t),basePriceEurPerYear:base(t),monthlyPaymentEur:monthly(t),billingPeriod:period(t),contractEnd:contract(t),cancellationPeriod:cancel(t),address:address(t)}}
function score(r:BillAnalysisResult){return fields.reduce((n,k)=>n+(r[k].value!==null?1:0),0)}
async function ocrImage(file:File){await loadOcr();const u=URL.createObjectURL(file);const img=await new Promise<HTMLImageElement>((ok,no)=>{const i=new Image();i.onload=()=>{URL.revokeObjectURL(u);ok(i)};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error("IMAGE_FAILED"))};i.src=u});const max=3200,s=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));const c=document.createElement("canvas");c.width=Math.max(1,Math.round((img.naturalWidth||img.width)*s));c.height=Math.max(1,Math.round((img.naturalHeight||img.height)*s));const x=c.getContext("2d");if(!x)throw new Error("CANVAS_FAILED");x.drawImage(img,0,0,c.width,c.height);const w=await window.Tesseract.createWorker("deu",1,{workerPath:WORKER,langPath:LANG,corePath:CORE,workerBlobURL:false});try{const r=await timeout(w.recognize(c,{rotateAuto:true},{tessedit_pageseg_mode:"6",preserve_interword_spaces:"1",user_defined_dpi:"300"}),45000);return String(r?.data?.text||"")}finally{await w.terminate()}}
async function pdfText(file:File){const p=await pdfjs(),d=await p.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,a:string[]=[];for(let i=1;i<=Math.min(12,d.numPages);i++){const q=await d.getPage(i),c=await q.getTextContent(),s=(c.items as any[]).map(x=>typeof x?.str==="string"?x.str:"").join(" ");if(s.trim())a.push(s)}return a.join("\n")}
async function pdfOcr(file:File){const p=await pdfjs(),d=await p.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,w=await loadOcr().then(()=>window.Tesseract.createWorker("deu",1,{workerPath:WORKER,langPath:LANG,corePath:CORE,workerBlobURL:false})),a:string[]=[];try{for(let i=1;i<=Math.min(5,d.numPages);i++){const q=await d.getPage(i),v=q.getViewport({scale:2.2}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const x=c.getContext("2d");if(!x)continue;await q.render({canvasContext:x,viewport:v}).promise;const r=await timeout(w.recognize(c,{rotateAuto:true},{tessedit_pageseg_mode:"6",preserve_interword_spaces:"1",user_defined_dpi:"300"}),60000);a.push(String(r?.data?.text||""))}}finally{await w.terminate()}return a.join("\n")}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{if(typeof window!=="undefined"&&process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL){try{const c=new AbortController(),id=setTimeout(()=>c.abort(),30000),fd=new FormData();fd.append("file",file);const r=await fetch(process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL,{method:"POST",body:fd,signal:c.signal});clearTimeout(id);if(r.ok){const j=await r.json();if(j?.analysis)return j.analysis as BillAnalysisResult}}catch{}}let raw="",r:BillAnalysisResult=emptyBillAnalysis();if(file.type==="application/pdf"||/\.pdf$/i.test(file.name)){try{raw=await timeout(pdfText(file),20000)}catch{}r=parseBillText(raw);if(score(r)<3){try{const o=await pdfOcr(file);r=parseBillText([raw,o].filter(Boolean).join("\n"))}catch{}}}else{try{raw=await ocrImage(file);r=parseBillText(raw)}catch{}}return r}
