export type BillAnalysisField={value:string|number|null;confidence:"high"|"medium"|"low"|"unknown";source:"document"|"not_detected"};
export type BillAnalysisResult={energyType:BillAnalysisField;provider:BillAnalysisField;tariffName:BillAnalysisField;annualConsumptionKwh:BillAnalysisField;workPriceCtPerKwh:BillAnalysisField;basePriceEurPerYear:BillAnalysisField;monthlyPaymentEur:BillAnalysisField;billingPeriod:BillAnalysisField;contractEnd:BillAnalysisField;cancellationPeriod:BillAnalysisField;address:BillAnalysisField};
const keys=(Object.keys({energyType:0,provider:0,tariffName:0,annualConsumptionKwh:0,workPriceCtPerKwh:0,basePriceEurPerYear:0,monthlyPaymentEur:0,billingPeriod:0,contractEnd:0,cancellationPeriod:0,address:0}) as Array<keyof BillAnalysisResult>);
const empty=():BillAnalysisField=>({value:null,confidence:"unknown",source:"not_detected"});
const field=(v:string|number|null,c:BillAnalysisField["confidence"]="medium"):BillAnalysisField=>v===null||v===""?empty():{value:v,confidence:c,source:"document"};
export function emptyBillAnalysis():BillAnalysisResult{return Object.fromEntries(keys.map(k=>[k,empty()])) as BillAnalysisResult;}
declare global{interface Window{Tesseract?:any}}
declare const process:{env:Record<string,string|undefined>};
const OCR_SCRIPTS=["https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js","https://unpkg.com/tesseract.js@5.1.1/dist/tesseract.min.js"];
const WORKER_URL="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/worker.min.js";
const PDF_URL="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.54/pdf.min.mjs";
const PDF_WORKER="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.54/pdf.worker.min.mjs";
let ocrLoader:Promise<void>|null=null,workerPromise:Promise<any>|null=null,pdfPromise:Promise<any>|null=null;
function loadOcr(){if(typeof document==="undefined")return Promise.reject(new Error("OCR_UNAVAILABLE"));if(window.Tesseract?.createWorker)return Promise.resolve();if(ocrLoader)return ocrLoader;ocrLoader=(async()=>{let last:any;for(const src of OCR_SCRIPTS){try{await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.async=true;s.crossOrigin="anonymous";s.onload=()=>resolve();s.onerror=()=>reject(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(s)});if(window.Tesseract?.createWorker)return;last=new Error("OCR_LIBRARY_LOAD_FAILED")}catch(e){last=e}}throw last||new Error("OCR_LIBRARY_LOAD_FAILED")})().catch(e=>{ocrLoader=null;throw e});return ocrLoader;}
async function getWorker(){await loadOcr();if(workerPromise)return workerPromise;workerPromise=window.Tesseract.createWorker("deu",1,{workerPath:WORKER_URL,logger:()=>undefined}).catch((e:any)=>{workerPromise=null;throw e});return workerPromise;}
function withTimeout<T>(p:Promise<T>,ms:number){return new Promise<T>((resolve,reject)=>{const id=setTimeout(()=>reject(new Error("TIMEOUT")),ms);p.then(v=>{clearTimeout(id);resolve(v)},e=>{clearTimeout(id);reject(e)})});}
function norm(s:string){return s.replace(/\u00a0/g," ").replace(/[‐‑‒–—]/g,"-").replace(/\r/g,"\n").replace(/k\s*[wvw]\s*h/gi,"kWh").replace(/k\s*w\s*n/gi,"kWh").replace(/kwh/gi,"kWh").replace(/c\s*t\s*\/\s*k\s*w\s*h/gi,"ct/kWh").replace(/c\s*t\s*\/\s*kwh/gi,"ct/kWh").replace(/c[au]\s*kwh/gi,"ct/kWh").replace(/c[au]\s*\/\s*kwh/gi,"ct/kWh").replace(/c\s*t\s*kwh/gi,"ct/kWh").replace(/c\s*t\s*\/\s*kw\s*h/gi,"ct/kWh").replace(/grund[o0]reis|grundpre[i1]s|grundoeis/gi,"Grundpreis").replace(/arbeit\s*(?:s|ss)?\s*pre[i1]s|arbeitspre[il]s|ar[bp]atspre[i1]s/gi,"Arbeitspreis").replace(/verbrauch\s*spre[i1]s|verbrauchspre[il]s/gi,"Verbrauchspreis").replace(/jahresverh?rauch|jahresverhrauch/gi,"Jahresverbrauch").replace(/abg[o0]r[o0]chneter|abgerechneter|abger[e3]chneter/gi,"Abgerechneter").replace(/str[o0]m/gi,"Strom").replace(/\bg[a4]s\b/gi,"Gas").replace(/[ \t]+/g," ").replace(/\n[ \t]+/g,"\n");}
function numberValue(s:string){let x=s.replace(/\s/g,"").replace(/[^0-9,.-]/g,"");if(!x)return null;const c=x.lastIndexOf(","),d=x.lastIndexOf(".");if(c>=0&&d>=0)x=c>d?x.replace(/\./g,"").replace(",","."):x.replace(/,/g,"");else if(c>=0)x=x.replace(/\./g,"").replace(",",".");else if(/^[-+]?\d{1,3}\.\d{3}(?:\.\d{3})+$/.test(x))x=x.replace(/\./g,"");const n=Number(x);return Number.isFinite(n)?n:null;}
function collect(t:string,re:RegExp,min:number,max:number){const out:number[]=[];const r=new RegExp(re.source,re.flags.includes("g")?re.flags:re.flags+"g");let m:RegExpExecArray|null;while((m=r.exec(t))){const n=numberValue(m[1]);if(n!==null&&n>=min&&n<=max)out.push(n);}return out;}
function energy(t:string){if(/Stromrechnung|Stromverbrauch|Stromkosten|Stromtarif|OptimalStrom|ÖkoStrom|Energiekosten[^\n]*Strom/i.test(t))return field("Strom","high");if(/Gasrechnung|Gasverbrauch|Gaskosten|Gaslieferung|Erdgasverbrauch|Gastarif/i.test(t))return field("Gas","high");return field(/\bStrom\b|Elektrizität/i.test(t)?"Strom":/\bGas\b|Erdgas/i.test(t)?"Gas":null,"medium");}
function provider(t:string){const names=["ENTEGA","E.ON","goldgas","EnBW","Vattenfall","Mainova","RheinEnergie","Yello","LichtBlick","Naturstrom","eprimo","EWE","enercity","Süwag","MVV Energie","lekker Energie","Octopus Energy","Tibber","EWR","ESWE Versorgung"];for(const n of names)if(new RegExp(n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i").test(t))return field(n,"high");return empty();}
function tariff(t:string){const hits=[...t.matchAll(/Ihre\s+Energiekosten\s+([^\n]{3,120})/gi)].map(m=>m[1].trim()).filter(v=>!/^Zusammensetzung|^Steuern|^Abgaben/i.test(v));if(hits.length)return field(hits[hits.length-1],"high");const m=t.match(/(?:Tarifname|Produktname|Stromtarif|Gastarif)\s*[:\-]?\s*([^\n]{3,100})/i);return field(m?.[1]?.trim()||null,m?"medium":"unknown");}
function annual(t:string){const patterns=[/Abgerechneter\s+Verbrauch[\s\S]{0,900}?20\d{2}\s*\/\s*\d{2}\s*[:\-]?\s*((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/i,/20\d{2}\s*\/\s*\d{2}\s*[:\-]?\s*((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/i,/Jahresverbrauch[^\n]{0,220}?((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/i,/Summe[^\n]{0,180}?((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/i];for(const re of patterns){const m=t.match(re);const n=m?numberValue(m[1]):null;if(n!==null&&n>=300&&n<=100000)return field(n,"high");}const settled=t.match(/Abgerechneter\s+Verbrauch[\s\S]{0,1200}/i)?.[0]||"";const a=collect(settled,/((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/gi,300,100000);if(a.length)return field(Math.max(...a),"high");const all=collect(t,/((?:\d{1,3}(?:[.\s]\d{3})+|\d{4,8})(?:,\d+)?)\s*kWh/gi,300,100000);return field(all.length?Math.max(...all):null,all.length?"medium":"unknown");}
function work(t:string){const re=/([0-9]{1,3}[,.][0-9]{1,3})\s*(?:ct|cent|cu|ca|c)\s*(?:\/\s*)?(?:k+\s*k?\s*w\s*h|w\s*h)/gi;let a=collect(t,re,5,100);if(a.length)return field(Math.max(...a.map(n=>Math.round(n*100)/100)),"high");a=collect(t,/Arbeitspreis[^\n]{0,180}?([0-9]{1,3}[,.][0-9]{1,3})\s*(?:ct|cent|cu|ca|c)\s*(?:\/\s*)?(?:k+\s*k?\s*w\s*h|w\s*h)/gi,5,100);return field(a.length?Math.max(...a):null,a.length?"high":"unknown");}
function base(t:string){let a=collect(t,/Grundpreis[^\n]{0,180}?([0-9]{1,5}[,.][0-9]{1,2})\s*(?:€|EUR|E|Eu)\s*(?:\/\s*Jahr|pro\s+Jahr|jährlich)/gi,10,10000);if(a.length)return field(Math.max(...a.map(n=>Math.round(n*100)/100)),"high");a=collect(t,/Grundpreis[^\n]{0,180}?([0-9]{1,5}[,.][0-9]{1,2})\s*(?:€|EUR|E|Eu)\s*(?:\/\s*Monat|pro\s+Monat|monatlich)/gi,1,1000);return field(a.length?Math.round(Math.max(...a)*12*100)/100:null,a.length?"high":"unknown");}
function monthly(t:string){const a=collect(t,/(?:monatlicher\s+Abschlag|neuer\s+Abschlag|Abschlagszahlung|Abschlag|Abschiag)[\s\S]{0,120}?([0-9]{2,5}[,.][0-9]{1,2})\s*(?:€|EUR|E|Eu)/gi,10,10000);return field(a.length?Math.max(...a):null,a.length?"high":"unknown");}
const d=(s:string)=>s.replace(/\//g,".");
function period(t:string){const m=t.match(/(?:für\s+den\s+Zeitraum|Abrechnungszeitraum)[\s\S]{0,180}?(?:vom\s+)?(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})\s*(?:-|bis|–)\s*(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})/i);if(m)return field(`${d(m[1])} - ${d(m[2])}`,"high");return empty();}
function contract(t:string){const m=t.match(/(?:Vertragsende|Vertrag(?:slaufzeit)?\s*(?:bis|endet)|Mindestvertragslaufzeit)[^\n]{0,160}?(\d{1,2}[.\/]\d{1,2}[.\/]\d{2,4})/i);return field(m?.[1]?d(m[1]):null,m?"high":"unknown");}
function cancel(t:string){const m=t.match(/(?:Kündigungsfrist|kündbar)[^\n]{0,100}?([0-9]{1,3}\s*(?:Tage?|Wochen?|Monate?))/i);return field(m?.[1]||null,m?"high":"unknown");}
function address(t:string){const m=t.match(/(?:Lieferadresse|Verbrauchsstelle|Entnahmestelle|Lieferstelle)\s*[:\-]?\s*([^\n]{5,140})/i);return field(m?.[1]?.trim()||null,m?"medium":"unknown");}
export function parseBillText(raw:string):BillAnalysisResult{const t=norm(raw);return{energyType:energy(t),provider:provider(t),tariffName:tariff(t),annualConsumptionKwh:annual(t),workPriceCtPerKwh:work(t),basePriceEurPerYear:base(t),monthlyPaymentEur:monthly(t),billingPeriod:period(t),contractEnd:contract(t),cancellationPeriod:cancel(t),address:address(t)};}
function mergeText(results:BillAnalysisResult[]){const out=emptyBillAnalysis();for(const key of keys){const vals=results.map(r=>r[key]).filter(v=>v.value!==null);if(!vals.length)continue;if(key==="annualConsumptionKwh"||key==="workPriceCtPerKwh"||key==="basePriceEurPerYear"){const nums=vals.map(v=>v.value).filter((v):v is number=>typeof v==="number");if(nums.length)out[key]=field(Math.max(...nums),"high");else out[key]=vals[0];}else out[key]=vals.sort((a,b)=>(b.confidence==="high"?3:b.confidence==="medium"?2:1)-(a.confidence==="high"?3:a.confidence==="medium"?2:1))[0];}return out;}
function imageCanvas(img:HTMLImageElement){const max=3600,s=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));const c=document.createElement("canvas");c.width=Math.max(1,Math.round((img.naturalWidth||img.width)*s));c.height=Math.max(1,Math.round((img.naturalHeight||img.height)*s));const x=c.getContext("2d");if(!x)throw new Error("CANVAS_FAILED");x.imageSmoothingEnabled=true;x.drawImage(img,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height),p=d.data;for(let i=0;i<p.length;i+=4){const y=0.299*p[i]+0.587*p[i+1]+0.114*p[i+2];const v=Math.max(0,Math.min(255,(y-128)*1.35+128));p[i]=p[i+1]=p[i+2]=v;}x.putImageData(d,0,0);return c;}
async function ocrImage(file:File){const w=await getWorker();const img=new Image();img.decoding="async";const url=URL.createObjectURL(file);try{await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error("IMAGE_LOAD_FAILED"));img.src=url});const c=imageCanvas(img);const first=await withTimeout(w.recognize(c),90000);const text=first?.data?.text||"";if(/Strom|E\.ON|Energiekosten|kWh/i.test(text))return text;const second=await withTimeout(w.recognize(file),90000);return second?.data?.text||text;}finally{URL.revokeObjectURL(url);}}
async function loadPdf(){if(pdfPromise)return pdfPromise;const imp=new Function("u","return import(u)") as (u:string)=>Promise<any>;pdfPromise=imp(PDF_URL).then(m=>{m.GlobalWorkerOptions.workerSrc=PDF_WORKER;return m}).catch(e=>{pdfPromise=null;throw e});return pdfPromise;}
async function pdfTextAndImages(file:File){const pdfjs=await loadPdf(),buf=await file.arrayBuffer(),doc=await pdfjs.getDocument({data:buf}).promise;let text="";const images:HTMLCanvasElement[]=[];for(let i=1;i<=doc.numPages&&i<=12;i++){const page=await doc.getPage(i);const content=await page.getTextContent();text+=content.items.map((x:any)=>x.str||"").join(" ")+"\n";if(!/kWh|E\.ON|Strom|Grundpreis/i.test(text)||text.length<400){const viewport=page.getViewport({scale:2});const c=document.createElement("canvas");c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);const ctx=c.getContext("2d");if(ctx){await page.render({canvasContext:ctx,viewport}).promise;images.push(c);}}}return{text,images};}
export async function analyzeBill(file:File):Promise<BillAnalysisResult>{const endpoint=typeof process!=="undefined"?process.env.NEXT_PUBLIC_BILL_ANALYSIS_URL:undefined;if(endpoint){try{const fd=new FormData();fd.append("file",file);const r=await fetch(endpoint,{method:"POST",body:fd});if(r.ok){const data=await r.json();if(data?.analysis)return data.analysis as BillAnalysisResult;}}catch{}}
if(file.type==="application/pdf"||/\.pdf$/i.test(file.name)){try{const p=await pdfTextAndImages(file);const native=parseBillText(p.text);if(native.annualConsumptionKwh.value!==null||native.workPriceCtPerKwh.value!==null||native.basePriceEurPerYear.value!==null)return native;const results:BillAnalysisResult[]=[];for(const c of p.images){const w=await getWorker();const r=await withTimeout(w.recognize(c),90000);results.push(parseBillText(r?.data?.text||""));}return mergeText(results);}catch{}}
return parseBillText(await ocrImage(file));}
